# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
Education Module - Tests
Owner: Basil

Tests for the education generate endpoint.
All tests use deterministic mock data and require no external network calls.
"""

import json
import pytest
import sys
import os
import shutil

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ppt_generator_stub import app, OUTPUT_DIR


@pytest.fixture
def client():
    """Create test client."""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


@pytest.fixture(autouse=True)
def cleanup_output():
    """Clean up output directory after each test."""
    yield
    # Cleanup generated files after test with retry for Windows file locking
    import gc
    import time
    gc.collect()  # Force garbage collection to release file handles
    
    if os.path.exists(OUTPUT_DIR):
        for f in os.listdir(OUTPUT_DIR):
            if f.endswith('.placeholder.txt'):
                filepath = os.path.join(OUTPUT_DIR, f)
                for attempt in range(3):
                    try:
                        os.remove(filepath)
                        break
                    except PermissionError:
                        time.sleep(0.1)  # Wait briefly and retry


class TestHealthEndpoint:
    """Tests for /health endpoint."""
    
    def test_health_returns_ok(self, client):
        """Health check should return healthy status."""
        response = client.get('/health')
        assert response.status_code == 200
        data = json.loads(response.data)
        assert data['status'] == 'healthy'
        assert data['module'] == 'education'
        assert data['port'] == 5004


class TestGenerateEndpoint:
    """Tests for /education/generate endpoint."""
    
    def test_generate_creates_artifact(self, client):
        """Should create placeholder file."""
        response = client.post(
            '/education/generate',
            json={
                'title': 'Test Presentation',
                'slides': [
                    {'heading': 'Introduction', 'bullets': ['Point 1', 'Point 2']},
                    {'heading': 'Conclusion', 'bullets': ['Summary']}
                ]
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        
        # Verify response structure
        assert 'artifact' in data
        assert 'note' in data
        assert data['note'] == 'use python-pptx in prod'
        assert data['slide_count'] == 2
        
        # Verify file was created
        filepath = data['filepath']
        assert os.path.exists(filepath)
        
        # Verify file content
        with open(filepath, 'r') as f:
            content = f.read()
            assert 'Test Presentation' in content
            assert 'Introduction' in content
            assert 'Point 1' in content
    
    def test_generate_missing_title(self, client):
        """Should return 400 when title is missing."""
        response = client.post(
            '/education/generate',
            json={
                'slides': [{'heading': 'Test', 'bullets': ['Point']}]
            },
            content_type='application/json'
        )
        
        assert response.status_code == 400
        data = json.loads(response.data)
        assert data['error'] == 'missing_field'
    
    def test_generate_missing_slides(self, client):
        """Should return 400 when slides is missing."""
        response = client.post(
            '/education/generate',
            json={'title': 'Test'},
            content_type='application/json'
        )
        
        assert response.status_code == 400
        data = json.loads(response.data)
        assert data['error'] == 'missing_field'
    
    def test_generate_invalid_slide_structure(self, client):
        """Should return 400 for invalid slide structure."""
        response = client.post(
            '/education/generate',
            json={
                'title': 'Test',
                'slides': [{'heading': 'No bullets'}]  # Missing bullets
            },
            content_type='application/json'
        )
        
        assert response.status_code == 400
        data = json.loads(response.data)
        assert data['error'] == 'invalid_slide'
    
    def test_generate_sanitizes_filename(self, client):
        """Should create safe filename from title."""
        response = client.post(
            '/education/generate',
            json={
                'title': 'Test: Special/Characters!',
                'slides': [{'heading': 'Intro', 'bullets': ['Point']}]
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        
        # Filename should not contain special characters
        assert '/' not in data['artifact']
        assert ':' not in data['artifact']
        assert '!' not in data['artifact']


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
