# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
WhatsApp Bot Generator - Tests
Owner: Adithyan

Tests for the WhatsApp generate endpoint.
All tests use deterministic mock data and require no external network calls.
"""

import json
import pytest
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import app


@pytest.fixture
def client():
    """Create test client."""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


class TestHealthEndpoint:
    """Tests for /health endpoint."""
    
    def test_health_returns_ok(self, client):
        """Health check should return healthy status."""
        response = client.get('/health')
        assert response.status_code == 200
        data = json.loads(response.data)
        assert data['status'] == 'healthy'
        assert data['module'] == 'whatsapp'
        assert data['port'] == 5001


class TestGenerateEndpoint:
    """Tests for /whatsapp/generate endpoint."""
    
    def test_generate_with_valid_template(self, client):
        """Should generate bot flow with valid template_id."""
        response = client.post(
            '/whatsapp/generate',
            json={
                'template_id': 'phone_repair_basic',
                'dry_run': True
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        
        # Verify response structure matches OpenAPI spec
        assert 'bot_flow' in data
        assert 'simulation' in data
        
        # Verify bot_flow structure
        bot_flow = data['bot_flow']
        assert 'id' in bot_flow
        assert 'name' in bot_flow
        assert 'steps' in bot_flow
        assert bot_flow['name'] == 'Phone Repair Bot'
        
        # Verify simulation is a list
        assert isinstance(data['simulation'], list)
        assert len(data['simulation']) > 0
        
        # Verify simulation structure
        for message in data['simulation']:
            assert 'from' in message
            assert 'text' in message
            assert message['from'] in ['bot', 'user']
    
    def test_generate_with_overrides(self, client):
        """Should apply overrides to template."""
        custom_prompt = "What brand and model is your device?"
        response = client.post(
            '/whatsapp/generate',
            json={
                'template_id': 'phone_repair_basic',
                'overrides': {'prompt_model': custom_prompt},
                'dry_run': True
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        assert 'bot_flow' in data
    
    def test_generate_missing_template_id(self, client):
        """Should return 400 when template_id is missing."""
        response = client.post(
            '/whatsapp/generate',
            json={'dry_run': True},
            content_type='application/json'
        )
        
        assert response.status_code == 400
        data = json.loads(response.data)
        assert 'error' in data
        assert data['error'] == 'missing_field'
    
    def test_generate_unknown_template(self, client):
        """Should return 404 for unknown template_id."""
        response = client.post(
            '/whatsapp/generate',
            json={'template_id': 'nonexistent_template'},
            content_type='application/json'
        )
        
        assert response.status_code == 404
        data = json.loads(response.data)
        assert 'error' in data
        assert data['error'] == 'not_found'
    
    def test_generate_empty_body(self, client):
        """Should return 400 for empty request body."""
        response = client.post(
            '/whatsapp/generate',
            data='',
            content_type='application/json'
        )
        
        assert response.status_code == 400
    
    def test_generate_complaint_template(self, client):
        """Should generate bot flow for complaint template."""
        response = client.post(
            '/whatsapp/generate',
            json={
                'template_id': 'complaint_basic',
                'dry_run': True
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        assert data['bot_flow']['name'] == 'Civic Complaints Bot'


class TestDeterministicOutput:
    """Tests ensuring deterministic output for demos."""
    
    def test_same_input_same_output(self, client):
        """Same input should always produce same output."""
        request_data = {
            'template_id': 'phone_repair_basic',
            'dry_run': True
        }
        
        response1 = client.post(
            '/whatsapp/generate',
            json=request_data,
            content_type='application/json'
        )
        response2 = client.post(
            '/whatsapp/generate',
            json=request_data,
            content_type='application/json'
        )
        
        data1 = json.loads(response1.data)
        data2 = json.loads(response2.data)
        
        # Simulation should be identical
        assert data1['simulation'] == data2['simulation']
        
        # Bot flow name should be identical
        assert data1['bot_flow']['name'] == data2['bot_flow']['name']


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
