# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
LeadGen Module - Tests
Owner: Lestlin

Tests for the leadgen analyze endpoint.
All tests use deterministic mock data and require no external network calls.
"""

import json
import pytest
import sys
import os

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from leadgen_stub import app


@pytest.fixture
def client():
    """Create test client."""
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


class TestHealthEndpoint:
    """Tests for /health endpoint."""
    
    def test_health_returns_ok(self, client):
        """Health check should return healthy status."""
        response = client.get('/health')
        assert response.status_code == 200
        data = json.loads(response.data)
        assert data['status'] == 'healthy'
        assert data['module'] == 'leadgen'
        assert data['port'] == 5003


class TestAnalyzeEndpoint:
    """Tests for /leadgen/analyze endpoint."""
    
    def test_analyze_with_valid_case(self, client):
        """Should return recommendations for valid case."""
        response = client.post(
            '/leadgen/analyze',
            json={
                'case_text': 'Vehicle theft reported near MG Road',
                'case_id': 'CASE-TEST-001'
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        
        # Verify response structure
        assert 'case_id' in data
        assert 'recommendations' in data
        assert data['case_id'] == 'CASE-TEST-001'
        
        # Must have at least 3 recommendations
        assert len(data['recommendations']) >= 3
        
        # Each recommendation must have step and confidence
        for rec in data['recommendations']:
            assert 'step' in rec
            assert 'confidence' in rec
            assert 0 <= rec['confidence'] <= 1
    
    def test_analyze_auto_generates_case_id(self, client):
        """Should auto-generate case_id if not provided."""
        response = client.post(
            '/leadgen/analyze',
            json={
                'case_text': 'Some test case description'
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        assert 'case_id' in data
        assert data['case_id'].startswith('CASE-AUTO-')
    
    def test_analyze_missing_case_text(self, client):
        """Should return 400 when case_text is missing."""
        response = client.post(
            '/leadgen/analyze',
            json={'case_id': 'CASE-TEST-002'},
            content_type='application/json'
        )
        
        assert response.status_code == 400
        data = json.loads(response.data)
        assert data['error'] == 'missing_field'
    
    def test_analyze_classifies_theft(self, client):
        """Should classify theft-related cases."""
        response = client.post(
            '/leadgen/analyze',
            json={
                'case_text': 'My car was stolen from the parking lot',
                'case_id': 'CASE-TEST-003'
            },
            content_type='application/json'
        )
        
        assert response.status_code == 200
        data = json.loads(response.data)
        assert data['case_type'] == 'theft'
    
    def test_analyze_deterministic_output(self, client):
        """Same input should produce same recommendations."""
        request_data = {
            'case_text': 'Vehicle theft reported',
            'case_id': 'CASE-TEST-004'
        }
        
        response1 = client.post(
            '/leadgen/analyze',
            json=request_data,
            content_type='application/json'
        )
        response2 = client.post(
            '/leadgen/analyze',
            json=request_data,
            content_type='application/json'
        )
        
        data1 = json.loads(response1.data)
        data2 = json.loads(response2.data)
        
        assert data1['recommendations'] == data2['recommendations']


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
