# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
Education Module - Stub Implementation
Owner: Basil
Port: 5004

This module generates educational presentations (PPT/PDF) from
structured content input.

TODO: Production Integration
1. Install and configure python-pptx
2. Implement PPTX generation with templates
3. Add PDF export capability
4. Implement custom styling/themes
5. Add image and chart support

API Endpoints:
- POST /education/generate - Generate presentation
- GET /health - Health check
"""

import os
from flask import Flask, request, jsonify

app = Flask(__name__)

# Output directory for generated files
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'output')


def ensure_output_dir():
    """Create output directory if it doesn't exist."""
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint."""
    return jsonify({"status": "healthy", "module": "education", "port": 5004})


@app.route('/education/generate', methods=['POST'])
def generate_presentation():
    """
    Generate a presentation from structured content.
    
    Request JSON:
    {
        "title": "Civic Duties 101",
        "slides": [
            {"heading": "Introduction", "bullets": ["Point 1", "Point 2"]},
            ...
        ]
    }
    
    Response JSON:
    {
        "artifact": "civic_duties_101.placeholder.txt",
        "note": "use python-pptx in prod"
    }
    """
    data = request.get_json()
    
    # Validate required fields
    if not data:
        return jsonify({
            "error": "bad_request",
            "message": "Request body must be JSON"
        }), 400
    
    title = data.get('title')
    if not title:
        return jsonify({
            "error": "missing_field",
            "message": "title is required"
        }), 400
    
    slides = data.get('slides')
    if not slides or not isinstance(slides, list):
        return jsonify({
            "error": "missing_field",
            "message": "slides array is required"
        }), 400
    
    # Validate slide structure
    for i, slide in enumerate(slides):
        if 'heading' not in slide:
            return jsonify({
                "error": "invalid_slide",
                "message": f"Slide {i+1} missing 'heading'"
            }), 400
        if 'bullets' not in slide or not isinstance(slide['bullets'], list):
            return jsonify({
                "error": "invalid_slide",
                "message": f"Slide {i+1} missing 'bullets' array"
            }), 400
    
    # Generate placeholder file (stub)
    ensure_output_dir()
    
    # Create safe filename
    safe_title = "".join(c if c.isalnum() or c in (' ', '_') else '_' for c in title)
    safe_title = safe_title.replace(' ', '_').lower()
    filename = f"{safe_title}.placeholder.txt"
    filepath = os.path.join(OUTPUT_DIR, filename)
    
    # Write placeholder content
    with open(filepath, 'w') as f:
        f.write(f"# {title}\n")
        f.write(f"# Generated by CivicAid Education Module\n")
        f.write(f"# Date: 2026-02-05\n")
        f.write("#" + "=" * 50 + "\n\n")
        
        for i, slide in enumerate(slides, 1):
            f.write(f"## Slide {i}: {slide['heading']}\n\n")
            for bullet in slide['bullets']:
                f.write(f"  • {bullet}\n")
            f.write("\n")
        
        f.write("#" + "=" * 50 + "\n")
        f.write("# TODO: Replace with actual PPTX using python-pptx\n")
    
    # TODO: In production:
    # 1. Use python-pptx to create actual PPTX file
    # 2. Apply template styling
    # 3. Add images and charts if provided
    # 4. Optionally convert to PDF
    
    return jsonify({
        "artifact": filename,
        "filepath": filepath,
        "slide_count": len(slides),
        "note": "use python-pptx in prod"
    })


if __name__ == '__main__':
    ensure_output_dir()
    print("=" * 50)
    print("Education Module - Starting on port 5004")
    print("=" * 50)
    print(f"\nOutput directory: {OUTPUT_DIR}")
    print("\nAvailable endpoints:")
    print("  POST /education/generate - Generate presentation")
    print("  GET  /health             - Health check")
    print("\nDemo command:")
    print('  curl -X POST http://localhost:5004/education/generate \\')
    print('    -H "Content-Type: application/json" \\')
    print('    -d \'{"title":"Test","slides":[{"heading":"Intro","bullets":["Point 1"]}]}\'')
    print("=" * 50)
    app.run(host='0.0.0.0', port=5004, debug=True)
