#!/bin/bash
# AUTOGENERATED BY CLAUDE: date=2026-02-05
# CivicAid - Contract Validation Script
#
# This script validates that all service implementations expose
# the endpoints declared in the OpenAPI contract.

set -e

echo "=========================================="
echo "CivicAid - Contract Validation"
echo "=========================================="
echo ""

FAILED=0
PASSED=0

check_endpoint() {
    local name=$1
    local port=$2
    local path=$3
    local method=$4
    local data=$5
    local expected_key=$6
    
    echo -n "Checking $name ($method $path)... "
    
    if [ "$method" = "GET" ]; then
        response=$(curl -s "http://localhost:$port$path" 2>/dev/null)
    else
        response=$(curl -s -X $method "http://localhost:$port$path" \
            -H "Content-Type: application/json" \
            -d "$data" 2>/dev/null)
    fi
    
    if echo "$response" | grep -q "\"$expected_key\""; then
        echo "✅ PASS"
        ((PASSED++))
    else
        echo "❌ FAIL (missing '$expected_key')"
        ((FAILED++))
    fi
}

echo "Validating endpoints against contracts/openapi.yaml..."
echo ""

# WhatsApp Module (Port 5001)
echo "📱 WhatsApp Module (Port 5001)"
echo "----------------------------------------"
check_endpoint "Health" 5001 "/health" "GET" "" "status"
check_endpoint "Generate" 5001 "/whatsapp/generate" "POST" \
    '{"template_id":"phone_repair_basic","dry_run":true}' "bot_flow"
echo ""

# Dispatch Module (Port 5002)
echo "📞 Dispatch Module (Port 5002)"
echo "----------------------------------------"
check_endpoint "Health" 5002 "/health" "GET" "" "status"
check_endpoint "Webhook" 5002 "/dispatch/webhook" "POST" \
    '{"call_id":"test","from":"+91999","primary_busy":true}' "action"
echo ""

# LeadGen Module (Port 5003)
echo "🔍 LeadGen Module (Port 5003)"
echo "----------------------------------------"
check_endpoint "Health" 5003 "/health" "GET" "" "status"
check_endpoint "Analyze" 5003 "/leadgen/analyze" "POST" \
    '{"case_text":"test case","case_id":"TEST-001"}' "recommendations"
echo ""

# Education Module (Port 5004)
echo "📚 Education Module (Port 5004)"
echo "----------------------------------------"
check_endpoint "Health" 5004 "/health" "GET" "" "status"
check_endpoint "Generate" 5004 "/education/generate" "POST" \
    '{"title":"Test","slides":[{"heading":"H","bullets":["B"]}]}' "artifact"
echo ""

echo "=========================================="
echo "Validation Summary"
echo "=========================================="
echo "  ✅ Passed: $PASSED"
echo "  ❌ Failed: $FAILED"
echo ""

if [ $FAILED -gt 0 ]; then
    echo "Contract validation FAILED. Please check the failing endpoints."
    exit 1
else
    echo "All contract validations PASSED!"
    exit 0
fi
