#!/bin/bash
# AUTOGENERATED BY CLAUDE: date=2026-02-05
# CivicAid - Run All Demos Script
# 
# This script starts all module servers, runs demo curl commands,
# displays outputs, and then terminates the servers.

set -e

echo "=========================================="
echo "CivicAid - Running All Module Demos"
echo "=========================================="
echo ""

# Change to project root
cd "$(dirname "$0")/.."

# Array to store PIDs
declare -a PIDS

cleanup() {
    echo ""
    echo "Shutting down servers..."
    for pid in "${PIDS[@]}"; do
        kill $pid 2>/dev/null || true
    done
    echo "All servers stopped."
}

trap cleanup EXIT

# Start all servers
echo "Starting module servers..."
echo ""

echo "📱 Starting WhatsApp module on port 5001..."
python -m modules.whatsapp.app &
PIDS+=($!)

echo "📞 Starting Dispatch module on port 5002..."
python -m modules.dispatch.dispatcher_stub &
PIDS+=($!)

echo "🔍 Starting LeadGen module on port 5003..."
python -m modules.leadgen.leadgen_stub &
PIDS+=($!)

echo "📚 Starting Education module on port 5004..."
python -m modules.education.ppt_generator_stub &
PIDS+=($!)

# Wait for servers to start
echo ""
echo "Waiting for servers to start..."
sleep 3

echo ""
echo "=========================================="
echo "Running Demo Commands"
echo "=========================================="

# Demo 1: WhatsApp
echo ""
echo "📱 DEMO 1: WhatsApp Bot Generator"
echo "----------------------------------------"
echo "Request:"
cat mock_data/whatsapp_sample_request.json
echo ""
echo "Response:"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d @mock_data/whatsapp_sample_request.json | python -m json.tool

# Demo 2: Dispatch
echo ""
echo ""
echo "📞 DEMO 2: Dispatch Webhook (primary_busy=true)"
echo "----------------------------------------"
echo "Request:"
cat mock_data/dispatch_sample_call.json
echo ""
echo "Response:"
curl -s -X POST http://localhost:5002/dispatch/webhook \
    -H "Content-Type: application/json" \
    -d @mock_data/dispatch_sample_call.json | python -m json.tool

# Demo 3: LeadGen
echo ""
echo ""
echo "🔍 DEMO 3: LeadGen Case Analysis"
echo "----------------------------------------"
echo "Request:"
cat mock_data/leadgen_sample_case.json
echo ""
echo "Response:"
curl -s -X POST http://localhost:5003/leadgen/analyze \
    -H "Content-Type: application/json" \
    -d @mock_data/leadgen_sample_case.json | python -m json.tool

# Demo 4: Education
echo ""
echo ""
echo "📚 DEMO 4: Education Presentation Generator"
echo "----------------------------------------"
echo "Request: {\"title\":\"Civic Duties\", \"slides\":[{\"heading\":\"Intro\",\"bullets\":[\"Point 1\"]}]}"
echo "Response:"
curl -s -X POST http://localhost:5004/education/generate \
    -H "Content-Type: application/json" \
    -d '{"title":"Civic Duties","slides":[{"heading":"Introduction","bullets":["What is civic duty","Why it matters"]},{"heading":"Voting","bullets":["Your right","Make it count"]}]}' | python -m json.tool

echo ""
echo ""
echo "=========================================="
echo "All Demos Complete!"
echo "=========================================="
echo ""
echo "Summary:"
echo "  ✅ WhatsApp: Generated bot flow with simulation"
echo "  ✅ Dispatch: Routed to fallback AI"
echo "  ✅ LeadGen: Generated 5 recommendations"
echo "  ✅ Education: Created placeholder presentation"
echo ""
