# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
AI Template Generator - Fireworks API Integration
Owner: Adithyan

This module uses Fireworks AI (Qwen3 235B) to dynamically generate
WhatsApp bot templates when a requested template doesn't exist.
"""

import os
import json
import requests
from typing import Dict, Any, Optional

# Load API key from environment
FIREWORKS_API_KEY = os.getenv('FIREWORKS_API_KEY', '')
FIREWORKS_MODEL = "accounts/fireworks/models/llama-v3p3-70b-instruct"
FIREWORKS_API_URL = "https://api.fireworks.ai/inference/v1/chat/completions"


# System prompt for template generation
SYSTEM_PROMPT = """You are a WhatsApp bot template generator. Generate templates in JSON format.

RULES:
1. Output ONLY the JSON object - no thinking, no explanation, no markdown
2. Start your response with { and end with }
3. Include 4-6 conversation steps
4. Include a realistic simulation

Exact JSON format required:
{"name": "Bot Name", "description": "Brief description", "steps": [{"id": "step1", "type": "message", "content": "Welcome!"}], "simulation": [{"from": "bot", "text": "Hi"}, {"from": "user", "text": "Hello"}]}

Step types: message (bot sends), input (asks user, has variable field), action (triggers something)
"""


def generate_template_with_ai(template_id: str, context: Optional[str] = None) -> Optional[Dict[str, Any]]:
    """
    Generate a bot template dynamically using Fireworks AI.
    
    Args:
        template_id: The requested template name (e.g., "restaurant_booking")
        context: Optional additional context for generation
    
    Returns:
        Generated template dict or None if generation fails
    """
    if not FIREWORKS_API_KEY:
        print("Warning: FIREWORKS_API_KEY not set")
        return None
    
    print(f"[AI] Generating template for: {template_id}")
    print(f"[AI] Using model: {FIREWORKS_MODEL}")
    
    # Convert template_id to human-readable request
    template_name = template_id.replace("_", " ").title()
    
    user_prompt = f"""Generate a WhatsApp bot template for: {template_name}

Template ID: {template_id}
"""
    if context:
        user_prompt += f"\nAdditional context: {context}"
    
    user_prompt += "\n\nGenerate a complete, realistic template with 4-6 steps and a full simulation conversation."
    
    try:
        response = requests.post(
            FIREWORKS_API_URL,
            headers={
                "Authorization": f"Bearer {FIREWORKS_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": FIREWORKS_MODEL,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt}
                ],
                "max_tokens": 4000,
                "temperature": 0.7
            },
            timeout=90  # Increased for thinking models
        )
        
        print(f"[AI] Response status: {response.status_code}")
        if response.status_code != 200:
            print(f"[AI] Fireworks API error: {response.status_code} - {response.text}")
            return None
        
        result = response.json()
        content = result.get("choices", [{}])[0].get("message", {}).get("content", "")
        
        # Extract JSON from thinking model output
        # Thinking models return reasoning text followed by the actual JSON
        content = content.strip()
        
        # Try to find JSON in the content using multiple strategies
        template = None
        
        # Strategy 1: Try parsing the whole content as JSON
        try:
            template = json.loads(content)
        except json.JSONDecodeError:
            pass
        
        # Strategy 2: Find JSON in code blocks
        if not template:
            import re
            # Look for JSON in code blocks
            code_block_match = re.search(r'```(?:json)?\s*(\{[\s\S]*?\})\s*```', content)
            if code_block_match:
                try:
                    template = json.loads(code_block_match.group(1))
                except json.JSONDecodeError:
                    pass
        
        # Strategy 3: Find the last complete JSON object in content
        if not template:
            # Find all potential JSON starts
            json_candidates = []
            brace_count = 0
            start_idx = None
            
            for i, char in enumerate(content):
                if char == '{':
                    if brace_count == 0:
                        start_idx = i
                    brace_count += 1
                elif char == '}':
                    brace_count -= 1
                    if brace_count == 0 and start_idx is not None:
                        json_candidates.append(content[start_idx:i+1])
                        start_idx = None
            
            # Try to parse each candidate, prefer ones with "name" and "steps"
            for candidate in reversed(json_candidates):  # Start from the last (most likely the answer)
                try:
                    parsed = json.loads(candidate)
                    if isinstance(parsed, dict) and ("name" in parsed or "steps" in parsed):
                        template = parsed
                        break
                except json.JSONDecodeError:
                    continue
        
        if not template:
            print(f"[AI] Could not extract JSON from response. Content preview: {content[:500]}")
            return None
        
        # Validate required fields
        if "name" not in template or "steps" not in template:
            print("[AI] Invalid template structure from AI - missing name or steps")
            return None
        
        # Add simulation if missing
        if "simulation" not in template:
            template["simulation"] = generate_default_simulation(template["steps"])
        
        print(f"[AI] Successfully generated template: {template.get('name', 'Unknown')}")
        return template
        
    except requests.exceptions.Timeout:
        print("[AI] Fireworks API timeout")
        return None
    except Exception as e:
        print(f"[AI] Generation error: {e}")
        return None


def generate_default_simulation(steps: list) -> list:
    """Generate a basic simulation from steps if AI didn't provide one."""
    simulation = []
    for step in steps:
        if step.get("type") == "message":
            simulation.append({"from": "bot", "text": step.get("content", "...")})
        elif step.get("type") == "input":
            simulation.append({"from": "bot", "text": step.get("content", "...")})
            simulation.append({"from": "user", "text": f"[User provides {step.get('variable', 'input')}]"})
    return simulation


def test_fireworks_connection() -> bool:
    """Test if Fireworks API is accessible."""
    if not FIREWORKS_API_KEY:
        return False
    
    try:
        response = requests.post(
            FIREWORKS_API_URL,
            headers={
                "Authorization": f"Bearer {FIREWORKS_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": FIREWORKS_MODEL,
                "messages": [{"role": "user", "content": "Say 'OK' if you can hear me."}],
                "max_tokens": 10
            },
            timeout=10
        )
        return response.status_code == 200
    except:
        return False


if __name__ == "__main__":
    # Load env from .env file for testing
    from dotenv import load_dotenv
    load_dotenv()
    
    print("Testing Fireworks AI connection...")
    if test_fireworks_connection():
        print("✅ Connection successful!")
        
        print("\nGenerating test template for 'restaurant_booking'...")
        template = generate_template_with_ai("restaurant_booking")
        if template:
            print("✅ Template generated:")
            print(json.dumps(template, indent=2))
        else:
            print("❌ Template generation failed")
    else:
        print("❌ Connection failed. Check your API key.")
