# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
WhatsApp Bot Generator - Flask Application
Owner: Adithyan
Port: 5001

This module provides a modular WhatsApp Bot Generator that creates
conversational flows based on configurable templates.

NEW: Uses Fireworks AI (Qwen3 235B) to dynamically generate templates
when a requested template doesn't exist.

API Endpoints:
- POST /whatsapp/generate - Generate bot flow from template
- GET /health - Health check
"""

import json
import os
from flask import Flask, request, jsonify
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import AI generator
try:
    from .ai_generator import generate_template_with_ai, test_fireworks_connection
    AI_AVAILABLE = True
except ImportError:
    try:
        from ai_generator import generate_template_with_ai, test_fireworks_connection
        AI_AVAILABLE = True
    except ImportError:
        AI_AVAILABLE = False
        print("Warning: AI generator not available")

app = Flask(__name__)

# Load templates from config file
TEMPLATES_PATH = os.path.join(os.path.dirname(__file__), 'config_templates.json')

def load_templates():
    """Load bot templates from config file."""
    try:
        with open(TEMPLATES_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_template(template_id: str, template: dict):
    """Save a generated template to config file for reuse."""
    templates = load_templates()
    templates[template_id] = template
    try:
        with open(TEMPLATES_PATH, 'w', encoding='utf-8') as f:
            json.dump(templates, f, indent=2, ensure_ascii=False)
        return True
    except Exception as e:
        print(f"Failed to save template: {e}")
        return False

# Deterministic simulation responses for demos (predefined templates)
DEMO_SIMULATIONS = {
    "phone_repair_basic": [
        {"from": "bot", "text": "Hello! Welcome to Phone Repair Service. How can I help you today?"},
        {"from": "user", "text": "My phone screen is cracked"},
        {"from": "bot", "text": "I'm sorry to hear that. Which model is it?"},
        {"from": "user", "text": "iPhone 14"},
        {"from": "bot", "text": "Got it! An iPhone 14 screen repair costs ₹8,500. Would you like to book a repair slot?"},
        {"from": "user", "text": "Yes please"},
        {"from": "bot", "text": "Great! I've booked a slot for you tomorrow at 10 AM. You'll receive a confirmation SMS shortly."}
    ],
    "complaint_basic": [
        {"from": "bot", "text": "Welcome to Civic Complaints Portal. Please describe your issue."},
        {"from": "user", "text": "There's a pothole on MG Road"},
        {"from": "bot", "text": "Thank you for reporting. Can you share the exact location or nearby landmark?"},
        {"from": "user", "text": "Near City Centre Mall"},
        {"from": "bot", "text": "Got it. Your complaint has been registered with ID: COMP-2026-001. The municipal team will inspect within 48 hours."}
    ],
    "default": [
        {"from": "bot", "text": "Hello! How can I assist you today?"},
        {"from": "user", "text": "I need help"},
        {"from": "bot", "text": "I'm here to help. Please tell me more about your issue."}
    ]
}


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint."""
    ai_status = "available" if AI_AVAILABLE else "unavailable"
    return jsonify({
        "status": "healthy", 
        "module": "whatsapp", 
        "port": 5001,
        "ai_generation": ai_status
    })


@app.route('/whatsapp/generate', methods=['POST'])
def generate_bot():
    """
    Generate a WhatsApp bot flow from a template.
    
    NEW: If template doesn't exist and AI is available, 
    dynamically generates a new template using Fireworks AI.
    
    Request JSON:
    {
        "template_id": "phone_repair_basic",
        "overrides": {"prompt_model": "Which model is it?"},
        "dry_run": true
    }
    
    Response JSON:
    {
        "bot_flow": { "id": "...", "name": "...", "steps": [...] },
        "simulation": [ {"from":"bot","text":"..."}, ... ],
        "ai_generated": true/false  // indicates if template was AI-generated
    }
    """
    data = request.get_json()
    
    # Validate required fields
    if not data:
        return jsonify({
            "error": "bad_request",
            "message": "Request body must be JSON"
        }), 400
    
    template_id = data.get('template_id')
    if not template_id:
        return jsonify({
            "error": "missing_field",
            "message": "template_id is required"
        }), 400
    
    # Load templates and check if template exists
    templates = load_templates()
    ai_generated = False
    
    if template_id not in templates:
        # Template doesn't exist - try AI generation
        if AI_AVAILABLE:
            print(f"Template '{template_id}' not found. Generating with AI...")
            context = data.get('context', '')  # Optional context for generation
            ai_template = generate_template_with_ai(template_id, context)
            
            if ai_template:
                # Save the generated template for future use
                template_data = {
                    "name": ai_template.get("name", template_id.replace("_", " ").title()),
                    "description": ai_template.get("description", "AI-generated template"),
                    "steps": ai_template.get("steps", []),
                    "metadata": {
                        "ai_generated": True,
                        "model": "qwen3-235b-a22b-instruct"
                    }
                }
                save_template(template_id, template_data)
                templates[template_id] = template_data
                ai_generated = True
                
                # Store AI-generated simulation
                if "simulation" in ai_template:
                    DEMO_SIMULATIONS[template_id] = ai_template["simulation"]
            else:
                return jsonify({
                    "error": "generation_failed",
                    "message": f"Failed to generate template for: {template_id}. AI unavailable or error occurred."
                }), 500
        else:
            return jsonify({
                "error": "not_found",
                "message": f"Unknown template_id: {template_id}. AI generation not available."
            }), 404
    
    template = templates[template_id]
    overrides = data.get('overrides', {})
    dry_run = data.get('dry_run', False)
    
    # Apply overrides to template
    steps = []
    for step in template.get('steps', []):
        step_copy = step.copy()
        for key, value in overrides.items():
            if key in step_copy.get('content', ''):
                step_copy['content'] = step_copy['content'].replace(f'{{{key}}}', value)
            if f'prompt_{step_copy.get("id", "")}' == key:
                step_copy['content'] = value
        steps.append(step_copy)
    
    # Generate bot flow
    bot_flow = {
        "id": f"flow_{template_id}_{hash(str(overrides)) % 100000:05d}",
        "name": template.get('name', template_id),
        "steps": steps,
        "created_at": "2026-02-05T00:45:00Z",
        "dry_run": dry_run,
        "ai_generated": ai_generated
    }
    
    # Get simulation (from AI if generated, else from predefined)
    simulation = DEMO_SIMULATIONS.get(template_id, DEMO_SIMULATIONS["default"])
    
    # Apply any text overrides to simulation
    if overrides.get('prompt_model'):
        simulation = [
            {"from": s["from"], "text": s["text"].replace("Which model is it?", overrides['prompt_model'])}
            if "model" in s["text"].lower() else s
            for s in simulation
        ]
    
    response = {
        "bot_flow": bot_flow,
        "simulation": simulation,
        "ai_generated": ai_generated
    }
    
    # TODO: If not dry_run, deploy to WhatsApp Business API
    # This would call adapters.deploy_bot_flow(bot_flow)
    
    return jsonify(response)


# Make module runnable
if __name__ == '__main__':
    print("=" * 60)
    print("WhatsApp Bot Generator - Starting on port 5001")
    print("=" * 60)
    print(f"\n[AI] Generation: {'ENABLED' if AI_AVAILABLE else 'DISABLED'}")
    if AI_AVAILABLE:
        print("   Using: Fireworks AI (Qwen3 235B)")
    print("\nAvailable endpoints:")
    print("  POST /whatsapp/generate - Generate bot flow")
    print("  GET  /health           - Health check")
    print("\nDemo commands:")
    print('  # Use existing template:')
    print('  curl -X POST http://localhost:5001/whatsapp/generate \\')
    print('    -H "Content-Type: application/json" \\')
    print('    -d \'{"template_id": "phone_repair_basic", "dry_run": true}\'')
    print('\n  # Generate NEW template with AI:')
    print('  curl -X POST http://localhost:5001/whatsapp/generate \\')
    print('    -H "Content-Type: application/json" \\')
    print('    -d \'{"template_id": "restaurant_booking", "dry_run": true}\'')
    print("=" * 60)
    app.run(host='0.0.0.0', port=5001, debug=True)

