# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
WhatsApp Bot Generator - Flask Application
Owner: Adithyan
Port: 5001

This module provides a modular WhatsApp Bot Generator that creates
conversational flows based on configurable templates.

NEW: Uses Fireworks AI (Qwen3 235B) to dynamically generate templates
when a requested template doesn't exist.

NEW: Modular Bot Builder - Build custom bots by selecting features
through a visual interface.

API Endpoints:
- POST /whatsapp/generate - Generate bot flow from template
- GET  /health - Health check
- GET  /whatsapp/modules - Get available modules catalog
- GET  /whatsapp/presets - Get industry presets
- POST /whatsapp/build - Build custom bot from selected modules
- POST /whatsapp/export-n8n - Export bot to n8n workflow
- POST /whatsapp/webhook - Handle incoming Twilio webhooks
- POST /whatsapp/simulate - Simulate conversation with bot
"""

import json
import os
from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import AI generator
try:
    from .ai_generator import generate_template_with_ai, test_fireworks_connection
    AI_AVAILABLE = True
except ImportError:
    try:
        from ai_generator import generate_template_with_ai, test_fireworks_connection
        AI_AVAILABLE = True
    except ImportError:
        AI_AVAILABLE = False
        print("Warning: AI generator not available")

# Import modular builder components
try:
    from .bot_builder_schema import (
        get_module_catalog, 
        get_industry_presets, 
        build_bot_config,
        AVAILABLE_MODULES,
        ModuleCategory
    )
    from .n8n_exporter import export_to_n8n, save_n8n_workflow
    BUILDER_AVAILABLE = True
except ImportError:
    try:
        from bot_builder_schema import (
            get_module_catalog, 
            get_industry_presets, 
            build_bot_config,
            AVAILABLE_MODULES,
            ModuleCategory
        )
        from n8n_exporter import export_to_n8n, save_n8n_workflow
        BUILDER_AVAILABLE = True
    except ImportError:
        BUILDER_AVAILABLE = False
        print("Warning: Bot builder components not available")

# Import Twilio webhook handler
try:
    from .twilio_handler import TwilioWebhookHandler
    TWILIO_AVAILABLE = True
except ImportError:
    try:
        from twilio_handler import TwilioWebhookHandler
        TWILIO_AVAILABLE = True
    except ImportError:
        TWILIO_AVAILABLE = False
        print("Warning: Twilio handler not available")

app = Flask(__name__)
CORS(app)  # Enable CORS for frontend

# Store active bot configurations in memory (use database in production)
ACTIVE_BOTS = {}

# Load templates from config file
TEMPLATES_PATH = os.path.join(os.path.dirname(__file__), 'config_templates.json')

def load_templates():
    """Load bot templates from config file."""
    try:
        with open(TEMPLATES_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_template(template_id: str, template: dict):
    """Save a generated template to config file for reuse."""
    templates = load_templates()
    templates[template_id] = template
    try:
        with open(TEMPLATES_PATH, 'w', encoding='utf-8') as f:
            json.dump(templates, f, indent=2, ensure_ascii=False)
        return True
    except Exception as e:
        print(f"Failed to save template: {e}")
        return False

# Deterministic simulation responses for demos (predefined templates)
DEMO_SIMULATIONS = {
    "phone_repair_basic": [
        {"from": "bot", "text": "Hello! Welcome to Phone Repair Service. How can I help you today?"},
        {"from": "user", "text": "My phone screen is cracked"},
        {"from": "bot", "text": "I'm sorry to hear that. Which model is it?"},
        {"from": "user", "text": "iPhone 14"},
        {"from": "bot", "text": "Got it! An iPhone 14 screen repair costs ₹8,500. Would you like to book a repair slot?"},
        {"from": "user", "text": "Yes please"},
        {"from": "bot", "text": "Great! I've booked a slot for you tomorrow at 10 AM. You'll receive a confirmation SMS shortly."}
    ],
    "complaint_basic": [
        {"from": "bot", "text": "Welcome to Civic Complaints Portal. Please describe your issue."},
        {"from": "user", "text": "There's a pothole on MG Road"},
        {"from": "bot", "text": "Thank you for reporting. Can you share the exact location or nearby landmark?"},
        {"from": "user", "text": "Near City Centre Mall"},
        {"from": "bot", "text": "Got it. Your complaint has been registered with ID: COMP-2026-001. The municipal team will inspect within 48 hours."}
    ],
    "default": [
        {"from": "bot", "text": "Hello! How can I assist you today?"},
        {"from": "user", "text": "I need help"},
        {"from": "bot", "text": "I'm here to help. Please tell me more about your issue."}
    ]
}


@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint."""
    ai_status = "available" if AI_AVAILABLE else "unavailable"
    builder_status = "available" if BUILDER_AVAILABLE else "unavailable"
    twilio_status = "available" if TWILIO_AVAILABLE else "unavailable"
    return jsonify({
        "status": "healthy", 
        "module": "whatsapp", 
        "port": 5001,
        "ai_generation": ai_status,
        "modular_builder": builder_status,
        "twilio_handler": twilio_status,
        "active_bots": len(ACTIVE_BOTS)
    })


# ============================================
# MODULAR BOT BUILDER ENDPOINTS
# ============================================

@app.route('/whatsapp/modules', methods=['GET'])
def get_modules():
    """
    Get the catalog of available bot modules.
    
    Response JSON:
    {
        "modules": { module_id: module_config, ... },
        "categories": ["greeting", "data_collection", ...]
    }
    """
    if not BUILDER_AVAILABLE:
        return jsonify({"error": "builder_unavailable", "message": "Bot builder not available"}), 503
    
    catalog = get_module_catalog()
    categories = [cat.value for cat in ModuleCategory]
    
    return jsonify({
        "modules": catalog,
        "categories": categories
    })


@app.route('/whatsapp/presets', methods=['GET'])
def get_presets():
    """
    Get industry preset configurations.
    
    Response JSON:
    {
        "presets": { preset_id: preset_config, ... }
    }
    """
    if not BUILDER_AVAILABLE:
        return jsonify({"error": "builder_unavailable", "message": "Bot builder not available"}), 503
    
    presets = get_industry_presets()
    return jsonify({"presets": presets})


@app.route('/whatsapp/build', methods=['POST'])
def build_bot():
    """
    Build a custom bot from selected modules.
    
    Request JSON:
    {
        "business_name": "My Business",
        "preset_id": "phone_repair",  // optional
        "modules": ["welcome_message", "collect_name", ...],
        "module_configs": { "welcome_message": { "message": "..." } },
        "dry_run": true
    }
    
    Response JSON:
    {
        "bot_config": { ... },
        "simulation": [ ... ],
        "n8n_workflow_available": true
    }
    """
    if not BUILDER_AVAILABLE:
        return jsonify({"error": "builder_unavailable", "message": "Bot builder not available"}), 503
    
    data = request.get_json()
    
    if not data:
        return jsonify({"error": "bad_request", "message": "Request body must be JSON"}), 400
    
    business_name = data.get('business_name', 'My Business')
    preset_id = data.get('preset_id')
    selected_modules = data.get('modules', [])
    module_configs = data.get('module_configs', {})
    dry_run = data.get('dry_run', True)
    
    # Build bot configuration
    bot_config = build_bot_config(
        business_name=business_name,
        selected_modules=selected_modules,
        module_configs=module_configs,
        preset_id=preset_id
    )
    
    # Generate simulation
    simulation = generate_simulation_from_config(bot_config)
    
    # Store in active bots if not dry run
    if not dry_run:
        ACTIVE_BOTS[bot_config['bot_id']] = bot_config
    
    return jsonify({
        "bot_config": bot_config,
        "simulation": simulation,
        "n8n_workflow_available": True,
        "dry_run": dry_run
    })


@app.route('/whatsapp/export-n8n', methods=['POST'])
def export_n8n_workflow():
    """
    Export bot configuration to n8n workflow JSON.
    
    Request JSON:
    {
        "bot_id": "bot_abc123",  // or provide full config
        "bot_config": { ... },
        "download": true  // return as file download
    }
    
    Response: JSON workflow or file download
    """
    if not BUILDER_AVAILABLE:
        return jsonify({"error": "builder_unavailable", "message": "Bot builder not available"}), 503
    
    data = request.get_json()
    
    if not data:
        return jsonify({"error": "bad_request", "message": "Request body must be JSON"}), 400
    
    # Get bot config from ID or direct config
    bot_config = None
    if 'bot_id' in data and data['bot_id'] in ACTIVE_BOTS:
        bot_config = ACTIVE_BOTS[data['bot_id']]
    elif 'bot_config' in data:
        bot_config = data['bot_config']
    
    if not bot_config:
        return jsonify({"error": "not_found", "message": "Bot configuration not found"}), 404
    
    # Export to n8n format
    workflow = export_to_n8n(bot_config)
    
    # Return as file download if requested
    if data.get('download', False):
        filename = f"n8n_workflow_{bot_config.get('bot_id', 'export')}.json"
        filepath = save_n8n_workflow(workflow, filename)
        return send_file(filepath, as_attachment=True, download_name=filename)
    
    return jsonify({
        "workflow": workflow,
        "import_instructions": {
            "step1": "Open n8n and go to Workflows",
            "step2": "Click 'Import from File' or 'Import from URL'",
            "step3": "Paste the workflow JSON or upload the file",
            "step4": "Configure your Twilio and Fireworks AI credentials",
            "step5": "Activate the workflow"
        }
    })


@app.route('/whatsapp/simulate', methods=['POST'])
def simulate_conversation():
    """
    Simulate a conversation with the bot.
    
    Request JSON:
    {
        "bot_id": "bot_abc123",
        "message": "Hello",
        "session_id": "user_123"  // for conversation state
    }
    
    Response JSON:
    {
        "response": "Bot response text",
        "next_step": "collect_name",
        "session_state": { ... }
    }
    """
    data = request.get_json()
    
    if not data:
        return jsonify({"error": "bad_request", "message": "Request body must be JSON"}), 400
    
    bot_id = data.get('bot_id')
    message = data.get('message', '')
    session_id = data.get('session_id', 'default')
    
    # Get bot config
    if bot_id and bot_id in ACTIVE_BOTS:
        bot_config = ACTIVE_BOTS[bot_id]
    else:
        # Use default simulation
        return jsonify({
            "response": f"Received: {message}. (No active bot configured)",
            "next_step": None,
            "session_state": {}
        })
    
    # Simple simulation logic (in production, use AI)
    response, next_step = simulate_bot_response(bot_config, message, session_id)
    
    return jsonify({
        "response": response,
        "next_step": next_step,
        "session_state": {"session_id": session_id}
    })


@app.route('/whatsapp/webhook', methods=['POST', 'GET'])
def twilio_webhook():
    """
    Handle incoming Twilio WhatsApp webhooks.
    
    GET: Webhook verification
    POST: Incoming message handling
    """
    if request.method == 'GET':
        # Webhook verification
        return request.args.get('hub.challenge', 'OK')
    
    if not TWILIO_AVAILABLE:
        return jsonify({"error": "twilio_unavailable", "message": "Twilio handler not available"}), 503
    
    # Parse incoming message
    data = request.form.to_dict() if request.form else request.get_json()
    
    handler = TwilioWebhookHandler(ACTIVE_BOTS)
    response = handler.handle_message(data)
    
    return response


# ============================================
# SIMULATION HELPERS
# ============================================

def generate_simulation_from_config(bot_config: dict) -> list:
    """Generate a simulation conversation from bot config."""
    simulation = []
    modules = bot_config.get('modules', {})
    flow = bot_config.get('flow', [])
    
    for module_id in flow:
        if module_id not in modules:
            continue
        
        module = modules[module_id]
        config = module.get('config', {})
        
        if module_id == 'welcome_message':
            simulation.append({
                "from": "bot",
                "text": config.get('message', 'Hello! Welcome!')
            })
        
        elif module_id == 'collect_name':
            simulation.append({
                "from": "bot", 
                "text": config.get('prompt', 'May I know your name?')
            })
            simulation.append({"from": "user", "text": "John Doe"})
        
        elif module_id == 'collect_phone':
            simulation.append({
                "from": "bot", 
                "text": config.get('prompt', 'Please share your contact number')
            })
            simulation.append({"from": "user", "text": "+91 98765 43210"})
        
        elif module_id == 'product_selection':
            items = config.get('items', [])
            if items:
                options = "\n".join([f"{i+1}. {item.get('label', item.get('id'))}" for i, item in enumerate(items)])
                simulation.append({
                    "from": "bot", 
                    "text": f"{config.get('prompt', 'Select an option:')}\n\n{options}"
                })
                simulation.append({"from": "user", "text": "1"})
        
        elif module_id == 'booking_appointment':
            simulation.append({
                "from": "bot",
                "text": config.get('prompt_date', 'Please select a date for your appointment')
            })
            simulation.append({"from": "user", "text": "Tomorrow"})
            simulation.append({
                "from": "bot",
                "text": config.get('prompt_time', 'Please select a time slot')
            })
            simulation.append({"from": "user", "text": "10 AM"})
            simulation.append({
                "from": "bot",
                "text": config.get('confirmation_message', 'Your appointment is confirmed for {date} at {time}').replace('{date}', 'tomorrow').replace('{time}', '10 AM')
            })
        
        elif module_id == 'complaint_registration':
            simulation.append({
                "from": "bot",
                "text": "Please describe your issue in detail."
            })
            simulation.append({"from": "user", "text": "There's a pothole on the main road"})
            if config.get('collect_image'):
                simulation.append({
                    "from": "bot",
                    "text": "Please share a photo of the issue (optional)"
                })
                simulation.append({"from": "user", "text": "[Photo shared]"})
            simulation.append({
                "from": "bot",
                "text": config.get('acknowledgment_message', 'Your complaint has been registered with ID: {complaint_id}').replace('{complaint_id}', 'COMP-2026-001').replace('{response_time}', '48 hours')
            })
        
        elif module_id == 'menu_navigation':
            options = config.get('options', [])
            if options:
                menu_text = config.get('menu_prompt', 'Please select an option:') + "\n\n"
                menu_text += "\n".join([f"{opt['number']}. {opt['label']}" for opt in options])
                simulation.append({"from": "bot", "text": menu_text})
                simulation.append({"from": "user", "text": "1"})
    
    # Add closing if no simulation generated
    if not simulation:
        simulation = [
            {"from": "bot", "text": f"Hello! Welcome to {bot_config.get('business_name', 'our service')}. How can I help you?"},
            {"from": "user", "text": "I need help"},
            {"from": "bot", "text": "I'm here to assist you. Please tell me what you need."}
        ]
    
    return simulation


def simulate_bot_response(bot_config: dict, message: str, session_id: str) -> tuple:
    """Simulate a single bot response."""
    # Simple keyword-based responses for demo
    message_lower = message.lower()
    
    modules = bot_config.get('modules', {})
    
    if any(word in message_lower for word in ['hi', 'hello', 'hey', 'start']):
        if 'welcome_message' in modules:
            return modules['welcome_message']['config'].get('message', 'Hello!'), 'collect_name'
    
    if any(word in message_lower for word in ['book', 'appointment', 'schedule']):
        if 'booking_appointment' in modules:
            return modules['booking_appointment']['config'].get('prompt_date', 'When would you like to book?'), 'booking_date'
    
    if any(word in message_lower for word in ['complaint', 'problem', 'issue', 'report']):
        if 'complaint_registration' in modules:
            return "Please describe your issue in detail.", 'complaint_description'
    
    return f"Thank you for your message. How else can I help you?", None


@app.route('/whatsapp/generate', methods=['POST'])
def generate_bot():
    """
    Generate a WhatsApp bot flow from a template.
    
    NEW: If template doesn't exist and AI is available, 
    dynamically generates a new template using Fireworks AI.
    
    Request JSON:
    {
        "template_id": "phone_repair_basic",
        "overrides": {"prompt_model": "Which model is it?"},
        "dry_run": true
    }
    
    Response JSON:
    {
        "bot_flow": { "id": "...", "name": "...", "steps": [...] },
        "simulation": [ {"from":"bot","text":"..."}, ... ],
        "ai_generated": true/false  // indicates if template was AI-generated
    }
    """
    data = request.get_json()
    
    # Validate required fields
    if not data:
        return jsonify({
            "error": "bad_request",
            "message": "Request body must be JSON"
        }), 400
    
    template_id = data.get('template_id')
    if not template_id:
        return jsonify({
            "error": "missing_field",
            "message": "template_id is required"
        }), 400
    
    # Load templates and check if template exists
    templates = load_templates()
    ai_generated = False
    
    if template_id not in templates:
        # Template doesn't exist - try AI generation
        if AI_AVAILABLE:
            print(f"Template '{template_id}' not found. Generating with AI...")
            context = data.get('context', '')  # Optional context for generation
            ai_template = generate_template_with_ai(template_id, context)
            
            if ai_template:
                # Save the generated template for future use
                template_data = {
                    "name": ai_template.get("name", template_id.replace("_", " ").title()),
                    "description": ai_template.get("description", "AI-generated template"),
                    "steps": ai_template.get("steps", []),
                    "metadata": {
                        "ai_generated": True,
                        "model": "qwen3-235b-a22b-instruct"
                    }
                }
                save_template(template_id, template_data)
                templates[template_id] = template_data
                ai_generated = True
                
                # Store AI-generated simulation
                if "simulation" in ai_template:
                    DEMO_SIMULATIONS[template_id] = ai_template["simulation"]
            else:
                return jsonify({
                    "error": "generation_failed",
                    "message": f"Failed to generate template for: {template_id}. AI unavailable or error occurred."
                }), 500
        else:
            return jsonify({
                "error": "not_found",
                "message": f"Unknown template_id: {template_id}. AI generation not available."
            }), 404
    
    template = templates[template_id]
    overrides = data.get('overrides', {})
    dry_run = data.get('dry_run', False)
    
    # Apply overrides to template
    steps = []
    for step in template.get('steps', []):
        step_copy = step.copy()
        for key, value in overrides.items():
            if key in step_copy.get('content', ''):
                step_copy['content'] = step_copy['content'].replace(f'{{{key}}}', value)
            if f'prompt_{step_copy.get("id", "")}' == key:
                step_copy['content'] = value
        steps.append(step_copy)
    
    # Generate bot flow
    bot_flow = {
        "id": f"flow_{template_id}_{hash(str(overrides)) % 100000:05d}",
        "name": template.get('name', template_id),
        "steps": steps,
        "created_at": "2026-02-05T00:45:00Z",
        "dry_run": dry_run,
        "ai_generated": ai_generated
    }
    
    # Get simulation (from AI if generated, else from predefined)
    simulation = DEMO_SIMULATIONS.get(template_id, DEMO_SIMULATIONS["default"])
    
    # Apply any text overrides to simulation
    if overrides.get('prompt_model'):
        simulation = [
            {"from": s["from"], "text": s["text"].replace("Which model is it?", overrides['prompt_model'])}
            if "model" in s["text"].lower() else s
            for s in simulation
        ]
    
    response = {
        "bot_flow": bot_flow,
        "simulation": simulation,
        "ai_generated": ai_generated
    }
    
    # TODO: If not dry_run, deploy to WhatsApp Business API
    # This would call adapters.deploy_bot_flow(bot_flow)
    
    return jsonify(response)


# Make module runnable
if __name__ == '__main__':
    print("=" * 60)
    print("WhatsApp Bot Generator - Starting on port 5001")
    print("=" * 60)
    print(f"\n[AI] Generation: {'ENABLED' if AI_AVAILABLE else 'DISABLED'}")
    if AI_AVAILABLE:
        print("   Using: Fireworks AI (Qwen3 235B)")
    print("\nAvailable endpoints:")
    print("  POST /whatsapp/generate - Generate bot flow")
    print("  GET  /health           - Health check")
    print("\nDemo commands:")
    print('  # Use existing template:')
    print('  curl -X POST http://localhost:5001/whatsapp/generate \\')
    print('    -H "Content-Type: application/json" \\')
    print('    -d \'{"template_id": "phone_repair_basic", "dry_run": true}\'')
    print('\n  # Generate NEW template with AI:')
    print('  curl -X POST http://localhost:5001/whatsapp/generate \\')
    print('    -H "Content-Type: application/json" \\')
    print('    -d \'{"template_id": "restaurant_booking", "dry_run": true}\'')
    print("=" * 60)
    app.run(host='0.0.0.0', port=5001, debug=True)

