# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
Bot Configuration API - Dynamic prompt generator for n8n integration
Owner: Adithyan

This module provides endpoints for:
1. Saving bot configurations from web UI
2. Generating dynamic AI prompts for n8n
3. Managing business-specific bot settings
"""

from flask import Flask, request, jsonify
from flask_cors import CORS
import json
import os
import re
import uuid
import requests
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Fireworks AI config
FIREWORKS_API_KEY = os.getenv('FIREWORKS_API_KEY', '')
FIREWORKS_MODEL = "accounts/fireworks/models/llama-v3p3-70b-instruct"
FIREWORKS_API_URL = "https://api.fireworks.ai/inference/v1/chat/completions"

# Twilio WhatsApp number (your sandbox or production number)
WHATSAPP_NUMBER = os.getenv('TWILIO_WHATSAPP_NUMBER', '+14155238886')

app = Flask(__name__)
CORS(app)  # Allow n8n to call this API

# Config file path
CONFIG_FILE = os.path.join(os.path.dirname(__file__), 'business_configs.json')

def load_configs():
    """Load all business configs"""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, 'r') as f:
            return json.load(f)
    return {}

def save_configs(configs):
    """Save business configs"""
    with open(CONFIG_FILE, 'w') as f:
        json.dump(configs, f, indent=2)

def generate_system_prompt(config):
    """Convert business config into AI system prompt"""
    
    business_name = config.get('business_info', {}).get('name', 'Business')
    bot_name = config.get('bot_name', 'Assistant')
    features = config.get('features', {})
    custom_prompts = config.get('custom_prompts', {})
    business_info = config.get('business_info', {})
    
    # Get AI-generated capabilities (from /api/bots/generate)
    ai_capabilities = config.get('capabilities', [])
    
    # Get AI-generated system prompt if available
    ai_system_prompt = config.get('system_prompt', '')
    
    # If AI already generated a system prompt, use it with enhancements
    if ai_system_prompt:
        enhanced_prompt = [
            "CRITICAL: You MUST stay in character at all times. Never break character or mention you are an AI/LLM.",
            "",
            ai_system_prompt,
            "",
            "IMPORTANT RULES:",
            f"- You ARE {bot_name}. Never say you are an AI or language model.",
            "- If you don't have real contact info, provide the business details below.",
            "- Keep responses brief and helpful.",
        ]
        
        # Add business info if available
        if business_info.get('phone'):
            enhanced_prompt.append(f"- Business Contact: {business_info['phone']}")
        if business_info.get('location'):
            enhanced_prompt.append(f"- Business Location: {business_info['location']}")
        if business_info.get('hours'):
            enhanced_prompt.append(f"- Business Hours: {business_info['hours']}")
            
        return "\n".join(enhanced_prompt)
    
    # Build dynamic prompt from checkboxes/config
    prompt_parts = [
        "CRITICAL: You MUST stay in character at all times. Never break character.",
        "",
        f"You are {bot_name} for {business_name}.",
        "Be helpful, friendly, and concise.",
        "",
        "YOUR CAPABILITIES:"
    ]
    
    # Add AI-generated capabilities first
    if ai_capabilities:
        for cap in ai_capabilities:
            prompt_parts.append(f"- {cap}")
    
    # Add checkbox-based features
    if features.get('phone_repair'):
        prompt_parts.append("- Phone Repair: Collect issue description, phone model, provide repair quotes")
    
    if features.get('model_inquiry'):
        prompt_parts.append("- Model Recommendations: Help customers choose phones based on budget and needs")
    
    if features.get('price_quotes'):
        prompt_parts.append("- Price Quotes: Provide accurate pricing for services/products")
    
    if features.get('appointment_booking'):
        prompt_parts.append("- Appointment Booking: Schedule service visits, collect preferred date/time")
    
    if features.get('order_tracking'):
        prompt_parts.append("- Order Tracking: Help customers check order/repair status")
    
    if features.get('complaint_registration'):
        prompt_parts.append("- Complaint Registration: Log customer complaints with details")
    
    if features.get('faq'):
        prompt_parts.append("- FAQ: Answer common questions about the business")
    
    # Add business info
    prompt_parts.append("")
    prompt_parts.append("BUSINESS INFORMATION:")
    
    if business_info.get('hours'):
        prompt_parts.append(f"- Business Hours: {business_info['hours']}")
    
    if business_info.get('location'):
        prompt_parts.append(f"- Location: {business_info['location']}")
    
    if business_info.get('phone'):
        prompt_parts.append(f"- Contact: {business_info['phone']}")
    
    # Add custom welcome if provided
    if custom_prompts.get('welcome'):
        prompt_parts.append("")
        prompt_parts.append(f"START CONVERSATION WITH: \"{custom_prompts['welcome']}\"")
    
    # Add conversation rules with stricter role enforcement
    prompt_parts.extend([
        "",
        "RULES:",
        f"- You ARE {bot_name}. NEVER say you are an AI or language model.",
        "- Keep responses brief (under 200 words)",
        "- Ask one question at a time",
        "- Confirm bookings before finalizing",
        "- If unsure, offer to connect with human support",
        "- If asked for contact, provide the business information above"
    ])
    
    return "\n".join(prompt_parts)



def generate_bot_from_description(description: str) -> dict:
    """
    Use AI to convert natural language description into bot configuration.
    
    Example input: "I run a phone repair shop. I want a bot that collects 
    customer issues, gives price quotes, and books appointments."
    """
    
    if not FIREWORKS_API_KEY:
        return {"error": "Fireworks API key not configured"}
    
    system_prompt = """You are a bot configuration generator. Given a business description, 
create a JSON configuration for a WhatsApp chatbot.

OUTPUT ONLY valid JSON with this structure:
{
    "bot_name": "Name of the bot",
    "business_info": {
        "name": "Business name",
        "type": "Type of business",
        "hours": "Business hours if mentioned",
        "location": "Location if mentioned"
    },
    "capabilities": ["list", "of", "things", "bot", "can", "do"],
    "welcome_message": "A friendly welcome message",
    "conversation_flow": [
        {"step": 1, "action": "greet", "message": "Welcome message"},
        {"step": 2, "action": "ask", "question": "What they need", "variable": "need"},
        ...
    ],
    "system_prompt": "Complete system prompt for the AI assistant"
}

Extract business details, capabilities, and create a natural conversation flow.
Output ONLY the JSON, no explanation."""

    try:
        response = requests.post(
            FIREWORKS_API_URL,
            headers={
                "Authorization": f"Bearer {FIREWORKS_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": FIREWORKS_MODEL,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Create a bot for this business:\n\n{description}"}
                ],
                "max_tokens": 2000,
                "temperature": 0.7
            },
            timeout=60
        )
        
        if response.status_code != 200:
            return {"error": f"AI API error: {response.status_code}"}
        
        content = response.json()['choices'][0]['message']['content'].strip()
        
        # Extract JSON from response
        # Try to find JSON in code blocks first
        code_block_match = re.search(r'```(?:json)?\s*(\{[\s\S]*?\})\s*```', content)
        if code_block_match:
            content = code_block_match.group(1)
        
        # Parse the JSON
        config = json.loads(content)
        return config
        
    except json.JSONDecodeError as e:
        return {"error": f"Failed to parse AI response: {str(e)}"}
    except requests.exceptions.Timeout:
        return {"error": "AI request timed out"}
    except Exception as e:
        return {"error": f"AI generation failed: {str(e)}"}


def generate_unique_id():
    """Generate a short unique business ID"""
    return uuid.uuid4().hex[:8]


def generate_whatsapp_link(business_id: str) -> dict:
    """Generate WhatsApp link and QR code URL for a business"""
    # Create the WhatsApp deep link
    # The START_{business_id} helps us identify which business config to use
    start_message = f"Hi_{business_id}"
    wa_link = f"https://wa.me/{WHATSAPP_NUMBER.replace('+', '')}?text={start_message}"
    
    # QR code URL using a free QR API
    qr_url = f"https://api.qrserver.com/v1/create-qr-code/?size=200x200&data={wa_link}"
    
    return {
        "whatsapp_link": wa_link,
        "qr_code_url": qr_url,
        "start_message": start_message
    }

# ===== API ENDPOINTS =====

@app.route('/api/bots/generate', methods=['POST'])
def generate_bot_endpoint():
    """
    Generate a bot from natural language description.
    
    Request body:
    {
        "description": "I run a phone repair shop. I want a bot..."
    }
    
    Returns:
    - Generated bot config
    - Unique business_id
    - WhatsApp link to share
    - QR code URL
    """
    data = request.json
    description = data.get('description', '')
    
    if not description or len(description) < 20:
        return jsonify({
            "error": "Please provide a detailed description (at least 20 characters)"
        }), 400
    
    print(f"[BOT GENERATOR] Creating bot from description: {description[:100]}...")
    
    # Generate bot config using AI
    ai_config = generate_bot_from_description(description)
    
    if "error" in ai_config:
        return jsonify(ai_config), 500
    
    # Create unique business ID
    business_id = generate_unique_id()
    
    # Generate WhatsApp links
    links = generate_whatsapp_link(business_id)
    
    # Prepare full config to save
    full_config = {
        "business_id": business_id,
        "original_description": description,
        "bot_name": ai_config.get("bot_name", "Assistant"),
        "business_info": ai_config.get("business_info", {}),
        "capabilities": ai_config.get("capabilities", []),
        "welcome_message": ai_config.get("welcome_message", "Hello! How can I help you?"),
        "conversation_flow": ai_config.get("conversation_flow", []),
        "system_prompt": ai_config.get("system_prompt", ""),
        "whatsapp_link": links["whatsapp_link"],
        "qr_code_url": links["qr_code_url"],
        "created_at": datetime.now().isoformat(),
        "status": "active"
    }
    
    # Save config
    configs = load_configs()
    configs[business_id] = full_config
    save_configs(configs)
    
    print(f"[BOT GENERATOR] Bot created successfully: {business_id}")
    
    return jsonify({
        "success": True,
        "business_id": business_id,
        "bot_name": full_config["bot_name"],
        "capabilities": full_config["capabilities"],
        "welcome_message": full_config["welcome_message"],
        "whatsapp_link": links["whatsapp_link"],
        "qr_code_url": links["qr_code_url"],
        "message": "Your bot is ready! Share the WhatsApp link with your customers."
    })


@app.route('/api/bots/create', methods=['POST'])
def create_bot():
    """Save a new bot configuration"""
    data = request.json
    business_id = data.get('business_id')
    
    if not business_id:
        return jsonify({"error": "business_id required"}), 400
    
    configs = load_configs()
    configs[business_id] = {
        **data,
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat()
    }
    save_configs(configs)
    
    return jsonify({
        "success": True,
        "business_id": business_id,
        "message": "Bot configuration saved!"
    })


@app.route('/api/bots/<business_id>', methods=['GET'])
def get_bot_config(business_id):
    """Get full bot configuration"""
    configs = load_configs()
    
    if business_id not in configs:
        return jsonify({"error": "Business not found"}), 404
    
    return jsonify(configs[business_id])


@app.route('/api/bots/prompt', methods=['GET'])
def get_bot_prompt():
    """
    Get dynamic system prompt for n8n AI Agent
    
    Query params:
    - business_id: The business identifier
    - phone: Optional, user's phone (for future routing)
    """
    business_id = request.args.get('business_id')
    
    if not business_id:
        # Default prompt if no business specified
        return jsonify({
            "system_prompt": "You are CivicAid Assistant. Help users with general inquiries. Be helpful and friendly."
        })
    
    configs = load_configs()
    
    if business_id not in configs:
        return jsonify({
            "system_prompt": "You are CivicAid Assistant. Help users with general inquiries. Be helpful and friendly.",
            "note": "Business not found, using default prompt"
        })
    
    config = configs[business_id]
    system_prompt = generate_system_prompt(config)
    
    return jsonify({
        "business_id": business_id,
        "bot_name": config.get('bot_name', 'Assistant'),
        "system_prompt": system_prompt
    })


@app.route('/api/bots/list', methods=['GET'])
def list_bots():
    """List all configured bots"""
    configs = load_configs()
    
    bots = []
    for business_id, config in configs.items():
        bots.append({
            "business_id": business_id,
            "bot_name": config.get('bot_name', 'Unnamed'),
            "created_at": config.get('created_at')
        })
    
    return jsonify({"bots": bots})


@app.route('/health', methods=['GET'])
def health():
    """Health check for n8n"""
    return jsonify({
        "status": "healthy",
        "service": "CivicAid Bot Config API",
        "timestamp": datetime.now().isoformat()
    })


if __name__ == '__main__':
    print("=" * 60)
    print("CivicAid Bot Config API - Starting on port 5002")
    print("=" * 60)
    print("\nEndpoints for n8n:")
    print("  GET  /api/bots/prompt?business_id=xxx  - Get AI prompt")
    print("  POST /api/bots/create                  - Save bot config")
    print("  GET  /api/bots/<id>                    - Get full config")
    print("  GET  /health                           - Health check")
    print("=" * 60)
    
    app.run(host='0.0.0.0', port=5002, debug=True)
