# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
Modular WhatsApp Bot Builder Schema
Owner: Adithyan

This module defines the modular components that can be combined
to build custom WhatsApp bots for different business use cases.

Each module is a self-contained feature that can be enabled/disabled
and configured through the UI.
"""

from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field, asdict
from enum import Enum
import json
import uuid


class ModuleCategory(Enum):
    """Categories of bot modules."""
    GREETING = "greeting"
    DATA_COLLECTION = "data_collection"
    ROUTING = "routing"
    ACTIONS = "actions"
    INTEGRATIONS = "integrations"
    AI_FEATURES = "ai_features"
    NOTIFICATIONS = "notifications"


class InputType(Enum):
    """Types of user input collection."""
    TEXT = "text"
    PHONE = "phone"
    EMAIL = "email"
    NUMBER = "number"
    DATE = "date"
    TIME = "time"
    LOCATION = "location"
    IMAGE = "image"
    DOCUMENT = "document"
    CHOICE = "choice"
    MULTI_CHOICE = "multi_choice"


@dataclass
class ModuleConfig:
    """Configuration for a single bot module."""
    id: str
    name: str
    description: str
    category: str
    enabled: bool = False
    required: bool = False
    config: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return asdict(self)


# ============================================
# AVAILABLE MODULES CATALOG
# ============================================

AVAILABLE_MODULES = {
    # GREETING MODULES
    "welcome_message": ModuleConfig(
        id="welcome_message",
        name="Welcome Message",
        description="Send a customizable welcome greeting when user starts conversation",
        category=ModuleCategory.GREETING.value,
        required=True,
        config={
            "message": "Hello! Welcome to {business_name}. How can I help you today?",
            "business_name": "",
            "include_menu": True
        }
    ),
    
    "business_hours": ModuleConfig(
        id="business_hours",
        name="Business Hours Check",
        description="Check if business is open and respond accordingly",
        category=ModuleCategory.GREETING.value,
        config={
            "opening_time": "09:00",
            "closing_time": "18:00",
            "days_open": ["monday", "tuesday", "wednesday", "thursday", "friday"],
            "closed_message": "We're currently closed. Our business hours are {hours}. Leave a message and we'll get back to you!"
        }
    ),
    
    # DATA COLLECTION MODULES
    "collect_name": ModuleConfig(
        id="collect_name",
        name="Collect Customer Name",
        description="Ask for and store customer's name",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "May I know your name?",
            "variable": "customer_name",
            "required": True
        }
    ),
    
    "collect_phone": ModuleConfig(
        id="collect_phone",
        name="Collect Phone Number",
        description="Ask for and validate phone number",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "Please share your contact number",
            "variable": "customer_phone",
            "validate": True,
            "country_code": "+91"
        }
    ),
    
    "collect_email": ModuleConfig(
        id="collect_email",
        name="Collect Email",
        description="Ask for and validate email address",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "What's your email address?",
            "variable": "customer_email",
            "validate": True
        }
    ),
    
    "collect_location": ModuleConfig(
        id="collect_location",
        name="Collect Location",
        description="Request user's location via WhatsApp location sharing",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "Please share your location",
            "variable": "customer_location",
            "accept_text": True
        }
    ),
    
    "collect_image": ModuleConfig(
        id="collect_image",
        name="Collect Image/Photo",
        description="Ask user to share an image (e.g., product photo, ID, issue photo)",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "Please share a photo",
            "variable": "customer_image",
            "purpose": "general",
            "max_size_mb": 5
        }
    ),
    
    "product_selection": ModuleConfig(
        id="product_selection",
        name="Product/Service Selection",
        description="Display products/services as interactive buttons or list",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "prompt": "What are you looking for?",
            "display_type": "buttons",  # buttons, list, numbered
            "items": [],  # Will be populated by user
            "variable": "selected_product"
        }
    ),
    
    "custom_questions": ModuleConfig(
        id="custom_questions",
        name="Custom Questions",
        description="Add custom questions to collect specific information",
        category=ModuleCategory.DATA_COLLECTION.value,
        config={
            "questions": [
                # {"id": "q1", "prompt": "Question text", "variable": "var_name", "type": "text"}
            ]
        }
    ),
    
    # ROUTING MODULES
    "intent_detection": ModuleConfig(
        id="intent_detection",
        name="AI Intent Detection",
        description="Use AI to understand user intent and route accordingly",
        category=ModuleCategory.ROUTING.value,
        config={
            "intents": [
                {"name": "inquiry", "keywords": ["info", "details", "price", "cost"], "route_to": "inquiry_flow"},
                {"name": "complaint", "keywords": ["problem", "issue", "broken", "not working"], "route_to": "complaint_flow"},
                {"name": "booking", "keywords": ["book", "appointment", "schedule", "reserve"], "route_to": "booking_flow"},
                {"name": "support", "keywords": ["help", "support", "assist"], "route_to": "support_flow"}
            ],
            "default_route": "general_flow",
            "use_ai": True
        }
    ),
    
    "keyword_routing": ModuleConfig(
        id="keyword_routing",
        name="Keyword-Based Routing",
        description="Route based on keywords in user message",
        category=ModuleCategory.ROUTING.value,
        config={
            "routes": [
                # {"keywords": ["repair", "fix"], "route_to": "repair_flow"}
            ],
            "case_sensitive": False
        }
    ),
    
    "menu_navigation": ModuleConfig(
        id="menu_navigation",
        name="Menu Navigation",
        description="Provide numbered menu options for navigation",
        category=ModuleCategory.ROUTING.value,
        config={
            "menu_prompt": "Please select an option:",
            "options": [
                {"number": 1, "label": "Product Inquiry", "route_to": "inquiry"},
                {"number": 2, "label": "Place Order", "route_to": "order"},
                {"number": 3, "label": "Track Order", "route_to": "tracking"},
                {"number": 4, "label": "Support", "route_to": "support"}
            ],
            "allow_text_input": True
        }
    ),
    
    # ACTION MODULES
    "booking_appointment": ModuleConfig(
        id="booking_appointment",
        name="Appointment Booking",
        description="Allow customers to book appointments with date/time selection",
        category=ModuleCategory.ACTIONS.value,
        config={
            "prompt_date": "Please select a date for your appointment",
            "prompt_time": "Please select a time slot",
            "available_slots": [],  # Dynamic from calendar
            "confirmation_message": "Your appointment is confirmed for {date} at {time}",
            "calendar_integration": None  # google, outlook, custom
        }
    ),
    
    "order_creation": ModuleConfig(
        id="order_creation",
        name="Order Creation",
        description="Create orders with product selection and quantity",
        category=ModuleCategory.ACTIONS.value,
        config={
            "allow_multiple_items": True,
            "collect_quantity": True,
            "show_prices": True,
            "require_confirmation": True,
            "order_prefix": "ORD"
        }
    ),
    
    "complaint_registration": ModuleConfig(
        id="complaint_registration",
        name="Complaint Registration",
        description="Register complaints with tracking ID generation",
        category=ModuleCategory.ACTIONS.value,
        config={
            "collect_description": True,
            "collect_image": True,
            "collect_priority": True,
            "priority_levels": ["Low", "Medium", "High", "Urgent"],
            "complaint_prefix": "COMP",
            "auto_acknowledge": True,
            "acknowledgment_message": "Your complaint has been registered with ID: {complaint_id}. We'll respond within {response_time}."
        }
    ),
    
    "payment_request": ModuleConfig(
        id="payment_request",
        name="Payment Request",
        description="Send payment links via WhatsApp",
        category=ModuleCategory.ACTIONS.value,
        config={
            "payment_gateway": "razorpay",  # razorpay, stripe, paytm
            "collect_amount": True,
            "fixed_amount": None,
            "currency": "INR",
            "payment_message": "Please complete your payment of {amount} using this link: {payment_link}"
        }
    ),
    
    "status_check": ModuleConfig(
        id="status_check",
        name="Status Check",
        description="Allow users to check order/complaint/booking status",
        category=ModuleCategory.ACTIONS.value,
        config={
            "prompt": "Please enter your reference ID to check status",
            "id_pattern": r"^[A-Z]{3,4}-\d{4,}$",
            "lookup_source": "api"  # api, database, webhook
        }
    ),
    
    # INTEGRATION MODULES
    "crm_integration": ModuleConfig(
        id="crm_integration",
        name="CRM Integration",
        description="Sync customer data with CRM (Zoho, Salesforce, HubSpot)",
        category=ModuleCategory.INTEGRATIONS.value,
        config={
            "crm_type": "zoho",  # zoho, salesforce, hubspot, custom
            "auto_create_lead": True,
            "update_on_interaction": True,
            "fields_to_sync": ["name", "phone", "email", "inquiry_type"]
        }
    ),
    
    "webhook_trigger": ModuleConfig(
        id="webhook_trigger",
        name="Webhook Trigger",
        description="Trigger external webhooks on specific events",
        category=ModuleCategory.INTEGRATIONS.value,
        config={
            "webhooks": [
                # {"event": "new_lead", "url": "https://...", "method": "POST"}
            ]
        }
    ),
    
    "google_sheets": ModuleConfig(
        id="google_sheets",
        name="Google Sheets Integration",
        description="Log data to Google Sheets for easy tracking",
        category=ModuleCategory.INTEGRATIONS.value,
        config={
            "sheet_id": "",
            "sheet_name": "Leads",
            "columns": ["timestamp", "name", "phone", "inquiry"]
        }
    ),
    
    # AI FEATURES
    "ai_chat": ModuleConfig(
        id="ai_chat",
        name="AI-Powered Chat",
        description="Use AI to handle general conversations and FAQs",
        category=ModuleCategory.AI_FEATURES.value,
        config={
            "model": "fireworks/llama-v3p3-70b",
            "system_prompt": "You are a helpful customer service assistant for {business_name}.",
            "knowledge_base": [],  # FAQs, product info
            "fallback_to_human": True,
            "max_ai_turns": 5
        }
    ),
    
    "sentiment_analysis": ModuleConfig(
        id="sentiment_analysis",
        name="Sentiment Analysis",
        description="Detect customer sentiment and escalate if negative",
        category=ModuleCategory.AI_FEATURES.value,
        config={
            "escalate_on_negative": True,
            "negative_threshold": 0.3,
            "escalation_message": "I understand you're frustrated. Let me connect you with a human agent."
        }
    ),
    
    # NOTIFICATION MODULES
    "confirmation_sms": ModuleConfig(
        id="confirmation_sms",
        name="Confirmation SMS",
        description="Send SMS confirmations for bookings/orders",
        category=ModuleCategory.NOTIFICATIONS.value,
        config={
            "enabled": True,
            "template": "Your {action_type} has been confirmed. Reference: {reference_id}"
        }
    ),
    
    "agent_notification": ModuleConfig(
        id="agent_notification",
        name="Agent Notification",
        description="Notify human agents when handoff is needed",
        category=ModuleCategory.NOTIFICATIONS.value,
        config={
            "notification_channel": "whatsapp",  # whatsapp, email, slack
            "agent_numbers": [],
            "include_context": True
        }
    ),
    
    "follow_up": ModuleConfig(
        id="follow_up",
        name="Automated Follow-up",
        description="Send automated follow-up messages after interactions",
        category=ModuleCategory.NOTIFICATIONS.value,
        config={
            "delay_hours": 24,
            "message": "Hi {name}! Just following up on your recent inquiry. Is there anything else we can help with?",
            "max_followups": 2
        }
    )
}


# ============================================
# INDUSTRY PRESETS
# ============================================

INDUSTRY_PRESETS = {
    "phone_repair": {
        "name": "Phone Repair Shop",
        "description": "Complete bot for phone/electronics repair businesses",
        "modules": [
            "welcome_message",
            "business_hours",
            "collect_name",
            "collect_phone",
            "product_selection",
            "collect_image",
            "booking_appointment",
            "confirmation_sms"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "Hello! Welcome to {business_name} Phone Repair. How can we help you today?",
                "include_menu": True
            },
            "product_selection": {
                "prompt": "What device needs repair?",
                "items": [
                    {"id": "iphone", "label": "iPhone", "icon": "📱"},
                    {"id": "samsung", "label": "Samsung", "icon": "📱"},
                    {"id": "oneplus", "label": "OnePlus", "icon": "📱"},
                    {"id": "other", "label": "Other Brand", "icon": "📱"}
                ]
            },
            "collect_image": {
                "prompt": "Please share a photo of the damage",
                "purpose": "damage_assessment"
            }
        }
    },
    
    "restaurant": {
        "name": "Restaurant / Food Delivery",
        "description": "Bot for restaurants with ordering and reservations",
        "modules": [
            "welcome_message",
            "business_hours",
            "menu_navigation",
            "collect_name",
            "collect_phone",
            "collect_location",
            "order_creation",
            "payment_request",
            "confirmation_sms"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "🍽️ Welcome to {business_name}! Ready to take your order.",
                "include_menu": True
            },
            "menu_navigation": {
                "options": [
                    {"number": 1, "label": "📋 View Menu", "route_to": "menu"},
                    {"number": 2, "label": "🛒 Place Order", "route_to": "order"},
                    {"number": 3, "label": "📍 Table Reservation", "route_to": "reservation"},
                    {"number": 4, "label": "📦 Track Order", "route_to": "tracking"}
                ]
            }
        }
    },
    
    "healthcare": {
        "name": "Healthcare / Clinic",
        "description": "Patient appointment and inquiry bot",
        "modules": [
            "welcome_message",
            "business_hours",
            "collect_name",
            "collect_phone",
            "product_selection",
            "booking_appointment",
            "status_check",
            "confirmation_sms",
            "agent_notification"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "🏥 Welcome to {business_name}. How can we assist you with your healthcare needs?",
                "include_menu": True
            },
            "product_selection": {
                "prompt": "What type of consultation do you need?",
                "items": [
                    {"id": "general", "label": "General Consultation"},
                    {"id": "specialist", "label": "Specialist Appointment"},
                    {"id": "lab", "label": "Lab Test Booking"},
                    {"id": "pharmacy", "label": "Pharmacy"}
                ]
            },
            "agent_notification": {
                "notification_channel": "whatsapp",
                "include_context": True
            }
        }
    },
    
    "ecommerce": {
        "name": "E-Commerce / Retail",
        "description": "Product inquiries, orders, and tracking",
        "modules": [
            "welcome_message",
            "ai_chat",
            "intent_detection",
            "collect_name",
            "collect_phone",
            "collect_email",
            "product_selection",
            "order_creation",
            "status_check",
            "payment_request",
            "crm_integration",
            "confirmation_sms"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "🛍️ Welcome to {business_name}! Browse products, track orders, or chat with us.",
                "include_menu": True
            },
            "ai_chat": {
                "system_prompt": "You are a helpful shopping assistant. Help customers find products, answer questions, and guide them through purchases."
            },
            "intent_detection": {
                "intents": [
                    {"name": "browse", "keywords": ["products", "catalog", "show"], "route_to": "catalog"},
                    {"name": "order", "keywords": ["buy", "order", "purchase"], "route_to": "order"},
                    {"name": "track", "keywords": ["track", "status", "where"], "route_to": "tracking"},
                    {"name": "return", "keywords": ["return", "refund", "exchange"], "route_to": "returns"}
                ]
            }
        }
    },
    
    "real_estate": {
        "name": "Real Estate",
        "description": "Property inquiries and site visit scheduling",
        "modules": [
            "welcome_message",
            "collect_name",
            "collect_phone",
            "collect_email",
            "product_selection",
            "custom_questions",
            "booking_appointment",
            "crm_integration",
            "agent_notification"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "🏠 Welcome to {business_name}! Looking to buy, sell, or rent property?",
                "include_menu": True
            },
            "product_selection": {
                "prompt": "What are you looking for?",
                "items": [
                    {"id": "buy", "label": "Buy Property"},
                    {"id": "rent", "label": "Rent Property"},
                    {"id": "sell", "label": "Sell Property"},
                    {"id": "commercial", "label": "Commercial Space"}
                ]
            },
            "custom_questions": {
                "questions": [
                    {"id": "budget", "prompt": "What's your budget range?", "variable": "budget", "type": "text"},
                    {"id": "location", "prompt": "Preferred location?", "variable": "preferred_location", "type": "text"},
                    {"id": "bedrooms", "prompt": "Number of bedrooms needed?", "variable": "bedrooms", "type": "number"}
                ]
            },
            "crm_integration": {
                "crm_type": "custom",
                "auto_create_lead": True
            }
        }
    },
    
    "civic_services": {
        "name": "Civic / Government Services",
        "description": "Complaint registration and service requests",
        "modules": [
            "welcome_message",
            "menu_navigation",
            "collect_name",
            "collect_phone",
            "collect_location",
            "collect_image",
            "complaint_registration",
            "status_check",
            "confirmation_sms",
            "webhook_trigger"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "🏛️ Welcome to {business_name} Civic Services Portal. Report issues or check complaint status.",
                "include_menu": True
            },
            "menu_navigation": {
                "options": [
                    {"number": 1, "label": "🚧 Report Road Issue", "route_to": "road_complaint"},
                    {"number": 2, "label": "💡 Report Street Light", "route_to": "light_complaint"},
                    {"number": 3, "label": "🚰 Water Supply Issue", "route_to": "water_complaint"},
                    {"number": 4, "label": "📋 Check Status", "route_to": "status"}
                ]
            },
            "complaint_registration": {
                "priority_levels": ["Low", "Medium", "High", "Emergency"],
                "complaint_prefix": "CVC"
            }
        }
    },
    
    "education": {
        "name": "Education / Training Institute",
        "description": "Course inquiries and enrollment",
        "modules": [
            "welcome_message",
            "ai_chat",
            "collect_name",
            "collect_phone",
            "collect_email",
            "product_selection",
            "custom_questions",
            "crm_integration",
            "agent_notification",
            "follow_up"
        ],
        "module_configs": {
            "welcome_message": {
                "message": "📚 Welcome to {business_name}! Explore our courses and start your learning journey.",
                "include_menu": True
            },
            "product_selection": {
                "prompt": "Which course category interests you?",
                "items": [
                    {"id": "tech", "label": "Technology & IT"},
                    {"id": "business", "label": "Business & Management"},
                    {"id": "design", "label": "Design & Creative"},
                    {"id": "language", "label": "Language Learning"}
                ]
            },
            "custom_questions": {
                "questions": [
                    {"id": "current_status", "prompt": "Are you a student or working professional?", "variable": "status", "type": "choice", "options": ["Student", "Working Professional", "Freelancer", "Other"]},
                    {"id": "experience", "prompt": "Any prior experience in this field?", "variable": "experience", "type": "text"}
                ]
            },
            "follow_up": {
                "delay_hours": 48,
                "message": "Hi {name}! Still interested in our courses? Reply to get a special discount!"
            }
        }
    }
}


def get_module_catalog() -> Dict[str, Dict]:
    """Get the full catalog of available modules."""
    catalog = {}
    for module_id, module in AVAILABLE_MODULES.items():
        catalog[module_id] = module.to_dict()
    return catalog


def get_industry_presets() -> Dict[str, Dict]:
    """Get all industry presets."""
    return INDUSTRY_PRESETS


def get_preset_config(preset_id: str) -> Optional[Dict]:
    """Get configuration for a specific industry preset."""
    return INDUSTRY_PRESETS.get(preset_id)


def build_bot_config(
    business_name: str,
    selected_modules: List[str],
    module_configs: Optional[Dict[str, Dict]] = None,
    preset_id: Optional[str] = None
) -> Dict[str, Any]:
    """
    Build a complete bot configuration from selected modules.
    
    Args:
        business_name: Name of the business
        selected_modules: List of module IDs to enable
        module_configs: Custom configurations for modules
        preset_id: Optional industry preset to use as base
    
    Returns:
        Complete bot configuration
    """
    config = {
        "bot_id": f"bot_{uuid.uuid4().hex[:8]}",
        "business_name": business_name,
        "created_at": "2026-02-05T00:00:00Z",
        "modules": {},
        "flow": [],
        "n8n_compatible": True
    }
    
    # Start with preset if provided
    if preset_id and preset_id in INDUSTRY_PRESETS:
        preset = INDUSTRY_PRESETS[preset_id]
        selected_modules = preset.get("modules", selected_modules)
        module_configs = module_configs or preset.get("module_configs", {})
    
    # Build module configurations
    for module_id in selected_modules:
        if module_id in AVAILABLE_MODULES:
            module = AVAILABLE_MODULES[module_id]
            module_dict = module.to_dict()
            module_dict["enabled"] = True
            
            # Apply custom configs
            if module_configs and module_id in module_configs:
                module_dict["config"].update(module_configs[module_id])
            
            # Replace business_name placeholder
            if "message" in module_dict["config"]:
                module_dict["config"]["message"] = module_dict["config"]["message"].replace(
                    "{business_name}", business_name
                )
            
            config["modules"][module_id] = module_dict
    
    # Generate flow order based on category priorities
    category_order = [
        ModuleCategory.GREETING.value,
        ModuleCategory.ROUTING.value,
        ModuleCategory.DATA_COLLECTION.value,
        ModuleCategory.ACTIONS.value,
        ModuleCategory.AI_FEATURES.value,
        ModuleCategory.INTEGRATIONS.value,
        ModuleCategory.NOTIFICATIONS.value
    ]
    
    for category in category_order:
        for module_id, module_config in config["modules"].items():
            if module_config["category"] == category:
                config["flow"].append(module_id)
    
    return config


if __name__ == "__main__":
    # Demo: Print available modules
    print("=" * 60)
    print("MODULAR WHATSAPP BOT BUILDER - AVAILABLE MODULES")
    print("=" * 60)
    
    catalog = get_module_catalog()
    by_category = {}
    
    for module_id, module in catalog.items():
        cat = module["category"]
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append(module)
    
    for category, modules in by_category.items():
        print(f"\n📁 {category.upper()}")
        for mod in modules:
            print(f"   ├─ {mod['id']}: {mod['name']}")
            print(f"   │     {mod['description']}")
    
    print("\n" + "=" * 60)
    print("INDUSTRY PRESETS")
    print("=" * 60)
    
    for preset_id, preset in get_industry_presets().items():
        print(f"\n🏢 {preset['name']}")
        print(f"   {preset['description']}")
        print(f"   Modules: {', '.join(preset['modules'][:5])}...")
