#!/bin/bash
# AUTOGENERATED BY CLAUDE: date=2026-02-05
# WhatsApp Module - Demo Script
# Owner: Adithyan

echo "=========================================="
echo "WhatsApp Bot Generator - Demo"
echo "=========================================="
echo ""

# Check if server is running
if ! curl -s http://localhost:5001/health > /dev/null 2>&1; then
    echo "⚠️  Server not running. Starting server..."
    echo "Run: python -m modules.whatsapp.app"
    exit 1
fi

echo "✅ Server is running on port 5001"
echo ""

echo "📱 Demo 1: Generate Phone Repair Bot"
echo "--------------------------------------"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d '{"template_id": "phone_repair_basic", "dry_run": true}' | python -m json.tool

echo ""
echo ""

echo "📱 Demo 2: Generate Complaint Bot"
echo "--------------------------------------"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d '{"template_id": "complaint_basic", "dry_run": true}' | python -m json.tool

echo ""
echo ""

echo "📱 Demo 3: With Custom Overrides"
echo "--------------------------------------"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d '{"template_id": "phone_repair_basic", "overrides": {"prompt_model": "Which device brand?"}, "dry_run": true}' | python -m json.tool

echo ""
echo ""

echo "❌ Demo 4: Error - Missing Template ID"
echo "--------------------------------------"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d '{"dry_run": true}' | python -m json.tool

echo ""
echo ""

echo "❌ Demo 5: Error - Unknown Template"
echo "--------------------------------------"
curl -s -X POST http://localhost:5001/whatsapp/generate \
    -H "Content-Type: application/json" \
    -d '{"template_id": "unknown_template"}' | python -m json.tool

echo ""
echo "=========================================="
echo "Demo Complete!"
echo "=========================================="
