# AUTOGENERATED BY CLAUDE: date=2026-02-05
"""
n8n Workflow Exporter
Owner: Adithyan

This module generates n8n-compatible workflow JSON from bot configurations.
The exported workflows can be imported directly into n8n to run the WhatsApp bot.

Features:
- Twilio WhatsApp webhook integration
- Fireworks AI agent integration
- Conversation memory
- Error handling
- Multiple routing options
"""

import json
import uuid
from typing import Dict, List, Any, Optional
from datetime import datetime


class N8nWorkflowExporter:
    """Export bot configurations to n8n workflow format."""
    
    def __init__(self):
        self.node_id_counter = 0
        
    def _generate_node_id(self) -> str:
        """Generate unique node ID."""
        self.node_id_counter += 1
        return str(uuid.uuid4())
    
    def _get_position(self, index: int, row: int = 0) -> List[int]:
        """Calculate node position in canvas."""
        x = 250 + (index * 200)
        y = 300 + (row * 150)
        return [x, y]
    
    def export_workflow(
        self,
        bot_config: Dict[str, Any],
        twilio_credentials: Optional[Dict] = None,
        ai_credentials: Optional[Dict] = None
    ) -> Dict[str, Any]:
        """
        Export bot configuration to n8n workflow JSON.
        
        Args:
            bot_config: Bot configuration from build_bot_config()
            twilio_credentials: Twilio API credentials
            ai_credentials: Fireworks AI credentials
        
        Returns:
            n8n workflow JSON
        """
        self.node_id_counter = 0
        
        workflow = {
            "name": f"WhatsApp Bot - {bot_config.get('business_name', 'Custom')}",
            "nodes": [],
            "connections": {},
            "active": False,
            "settings": {
                "executionOrder": "v1"
            },
            "versionId": str(uuid.uuid4()),
            "meta": {
                "instanceId": str(uuid.uuid4()),
                "templateCreatedBy": "CivicAid Bot Builder"
            },
            "id": str(uuid.uuid4()),
            "tags": ["whatsapp", "civicaid", "auto-generated"]
        }
        
        nodes = []
        connections = {}
        
        # 1. Twilio WhatsApp Webhook (Trigger)
        webhook_node = self._create_twilio_webhook_node(0)
        nodes.append(webhook_node)
        
        # 2. Extract Message Data
        extract_node = self._create_extract_message_node(1)
        nodes.append(extract_node)
        connections[webhook_node["id"]] = {"main": [[{"node": extract_node["id"], "type": "main", "index": 0}]]}
        
        # 3. Route by Keywords/Intent
        route_node = self._create_route_node(bot_config, 2)
        nodes.append(route_node)
        connections[extract_node["id"]] = {"main": [[{"node": route_node["id"], "type": "main", "index": 0}]]}
        
        # 4. AI Agent Node
        ai_node = self._create_ai_agent_node(bot_config, 3)
        nodes.append(ai_node)
        
        # 5. Fireworks AI Model
        model_node = self._create_fireworks_model_node(4)
        nodes.append(model_node)
        
        # 6. Conversation Memory
        memory_node = self._create_memory_node(5)
        nodes.append(memory_node)
        
        # Connect route to AI agent
        route_outputs = []
        for i in range(4):  # Multiple route outputs
            route_outputs.append([{"node": ai_node["id"], "type": "main", "index": 0}])
        connections[route_node["id"]] = {"main": route_outputs}
        
        # Connect model and memory to AI agent (as sub-nodes)
        connections[model_node["id"]] = {"ai_languageModel": [[{"node": ai_node["id"], "type": "ai_languageModel", "index": 0}]]}
        connections[memory_node["id"]] = {"ai_memory": [[{"node": ai_node["id"], "type": "ai_memory", "index": 0}]]}
        
        # 7. Prepare Twilio Response
        prepare_node = self._create_prepare_response_node(6)
        nodes.append(prepare_node)
        connections[ai_node["id"]] = {"main": [[{"node": prepare_node["id"], "type": "main", "index": 0}]]}
        
        # 8. Send WhatsApp Response
        send_node = self._create_send_whatsapp_node(7)
        nodes.append(send_node)
        connections[prepare_node["id"]] = {"main": [[{"node": send_node["id"], "type": "main", "index": 0}]]}
        
        # 9. Respond to Twilio
        respond_node = self._create_respond_node(8)
        nodes.append(respond_node)
        connections[send_node["id"]] = {"main": [[{"node": respond_node["id"], "type": "main", "index": 0}]]}
        
        # 10. Error Handler (separate flow)
        error_handler = self._create_error_handler_node(0, row=1)
        nodes.append(error_handler)
        
        # 11. Prepare Error Response
        error_prepare = self._create_prepare_error_response_node(1, row=1)
        nodes.append(error_prepare)
        connections[error_handler["id"]] = {"main": [[{"node": error_prepare["id"], "type": "main", "index": 0}]]}
        
        # 12. Send Error Message
        error_send = self._create_send_error_node(2, row=1)
        nodes.append(error_send)
        connections[error_prepare["id"]] = {"main": [[{"node": error_send["id"], "type": "main", "index": 0}]]}
        
        workflow["nodes"] = nodes
        workflow["connections"] = connections
        
        return workflow
    
    def _create_twilio_webhook_node(self, index: int) -> Dict:
        """Create Twilio WhatsApp Webhook node."""
        return {
            "id": self._generate_node_id(),
            "name": "Twilio WhatsApp Webhook",
            "type": "n8n-nodes-base.webhook",
            "typeVersion": 1.1,
            "position": self._get_position(index),
            "parameters": {
                "httpMethod": "POST",
                "path": "whatsapp-webhook",
                "responseMode": "responseNode",
                "options": {}
            },
            "webhookId": str(uuid.uuid4())
        }
    
    def _create_extract_message_node(self, index: int) -> Dict:
        """Create Extract Message Data node."""
        return {
            "id": self._generate_node_id(),
            "name": "Extract Message Data",
            "type": "n8n-nodes-base.set",
            "typeVersion": 3.4,
            "position": self._get_position(index),
            "parameters": {
                "mode": "manual",
                "duplicateItem": False,
                "assignments": {
                    "assignments": [
                        {
                            "id": str(uuid.uuid4()),
                            "name": "from_number",
                            "value": "={{ $json.From }}",
                            "type": "string"
                        },
                        {
                            "id": str(uuid.uuid4()),
                            "name": "message_body",
                            "value": "={{ $json.Body }}",
                            "type": "string"
                        },
                        {
                            "id": str(uuid.uuid4()),
                            "name": "message_sid",
                            "value": "={{ $json.MessageSid }}",
                            "type": "string"
                        },
                        {
                            "id": str(uuid.uuid4()),
                            "name": "to_number",
                            "value": "={{ $json.To }}",
                            "type": "string"
                        }
                    ]
                },
                "includeOtherFields": True,
                "options": {}
            }
        }
    
    def _create_route_node(self, bot_config: Dict, index: int) -> Dict:
        """Create Route by Keywords node."""
        # Get routing rules from bot config
        modules = bot_config.get("modules", {})
        routes = []
        
        if "intent_detection" in modules:
            intents = modules["intent_detection"].get("config", {}).get("intents", [])
            for intent in intents:
                routes.append({
                    "output": intent["name"].title(),
                    "conditions": {
                        "options": {
                            "caseSensitive": False,
                            "leftValue": "",
                            "typeValidation": "loose"
                        },
                        "conditions": [
                            {
                                "leftValue": "={{ $json.message_body.toLowerCase() }}",
                                "rightValue": "|".join(intent.get("keywords", [])),
                                "operator": {
                                    "type": "string",
                                    "operation": "regex"
                                }
                            }
                        ]
                    }
                })
        
        # Default routes
        if not routes:
            routes = [
                {
                    "output": "Booking Flow",
                    "conditions": {
                        "options": {"caseSensitive": False, "leftValue": ""},
                        "conditions": [
                            {
                                "leftValue": "={{ $json.message_body.toLowerCase() }}",
                                "rightValue": "book|appointment|schedule|reserve",
                                "operator": {"type": "string", "operation": "regex"}
                            }
                        ]
                    }
                },
                {
                    "output": "Complaint Flow",
                    "conditions": {
                        "options": {"caseSensitive": False, "leftValue": ""},
                        "conditions": [
                            {
                                "leftValue": "={{ $json.message_body.toLowerCase() }}",
                                "rightValue": "complaint|problem|issue|broken",
                                "operator": {"type": "string", "operation": "regex"}
                            }
                        ]
                    }
                },
                {
                    "output": "Status Check",
                    "conditions": {
                        "options": {"caseSensitive": False, "leftValue": ""},
                        "conditions": [
                            {
                                "leftValue": "={{ $json.message_body.toLowerCase() }}",
                                "rightValue": "status|track|check|where",
                                "operator": {"type": "string", "operation": "regex"}
                            }
                        ]
                    }
                }
            ]
        
        return {
            "id": self._generate_node_id(),
            "name": "Route by Keywords",
            "type": "n8n-nodes-base.switch",
            "typeVersion": 3.1,
            "position": self._get_position(index),
            "parameters": {
                "mode": "rules",
                "rules": {
                    "values": routes
                },
                "options": {
                    "fallbackOutput": "extra"
                }
            }
        }
    
    def _create_ai_agent_node(self, bot_config: Dict, index: int) -> Dict:
        """Create AI Agent node."""
        business_name = bot_config.get("business_name", "CivicAid")
        modules = bot_config.get("modules", {})
        
        # Build system prompt from modules
        system_prompt = f"You are a helpful WhatsApp assistant for {business_name}. "
        
        if "ai_chat" in modules:
            custom_prompt = modules["ai_chat"].get("config", {}).get("system_prompt", "")
            if custom_prompt:
                system_prompt = custom_prompt.replace("{business_name}", business_name)
        
        # Add module-specific instructions
        if "booking_appointment" in modules:
            system_prompt += "\nYou can help users book appointments. Collect their preferred date and time."
        if "complaint_registration" in modules:
            system_prompt += "\nYou can register complaints. Collect issue description, location, and optionally a photo."
        if "order_creation" in modules:
            system_prompt += "\nYou can help users place orders. Show available products and collect quantity."
        
        system_prompt += "\nAlways be polite, concise, and helpful. If you can't help, offer to connect with a human agent."
        
        return {
            "id": self._generate_node_id(),
            "name": "CivicAid AI Agent",
            "type": "@n8n/n8n-nodes-langchain.agent",
            "typeVersion": 1.7,
            "position": self._get_position(index),
            "parameters": {
                "text": "={{ $json.message_body }}",
                "options": {
                    "systemMessage": system_prompt,
                    "maxIterations": 10,
                    "returnIntermediateSteps": False
                }
            }
        }
    
    def _create_fireworks_model_node(self, index: int) -> Dict:
        """Create Fireworks AI Chat Model node."""
        return {
            "id": self._generate_node_id(),
            "name": "Fireworks AI Chat Model",
            "type": "@n8n/n8n-nodes-langchain.lmChatFireworks",
            "typeVersion": 1,
            "position": self._get_position(index, row=-1),
            "parameters": {
                "model": "accounts/fireworks/models/llama-v3p3-70b-instruct",
                "options": {
                    "temperature": 0.7,
                    "maxTokens": 1000
                }
            },
            "credentials": {
                "fireworksAiApi": {
                    "id": "fireworks_cred",
                    "name": "Fireworks AI account"
                }
            }
        }
    
    def _create_memory_node(self, index: int) -> Dict:
        """Create Conversation Memory node."""
        return {
            "id": self._generate_node_id(),
            "name": "Conversation Memory",
            "type": "@n8n/n8n-nodes-langchain.memoryBufferWindow",
            "typeVersion": 1.2,
            "position": self._get_position(index, row=-1),
            "parameters": {
                "sessionIdType": "customKey",
                "sessionKey": "={{ $json.from_number }}",
                "contextWindowLength": 10
            }
        }
    
    def _create_prepare_response_node(self, index: int) -> Dict:
        """Create Prepare Twilio Response node."""
        return {
            "id": self._generate_node_id(),
            "name": "Prepare Twilio Response",
            "type": "n8n-nodes-base.set",
            "typeVersion": 3.4,
            "position": self._get_position(index),
            "parameters": {
                "mode": "manual",
                "duplicateItem": False,
                "assignments": {
                    "assignments": [
                        {
                            "id": str(uuid.uuid4()),
                            "name": "response_text",
                            "value": "={{ $json.output }}",
                            "type": "string"
                        },
                        {
                            "id": str(uuid.uuid4()),
                            "name": "to",
                            "value": "={{ $('Extract Message Data').item.json.from_number }}",
                            "type": "string"
                        },
                        {
                            "id": str(uuid.uuid4()),
                            "name": "from",
                            "value": "={{ $('Extract Message Data').item.json.to_number }}",
                            "type": "string"
                        }
                    ]
                },
                "includeOtherFields": False,
                "options": {}
            }
        }
    
    def _create_send_whatsapp_node(self, index: int) -> Dict:
        """Create Send WhatsApp Response node."""
        return {
            "id": self._generate_node_id(),
            "name": "Send WhatsApp Response",
            "type": "n8n-nodes-base.twilio",
            "typeVersion": 1,
            "position": self._get_position(index),
            "parameters": {
                "operation": "send",
                "from": "={{ $json.from }}",
                "to": "={{ $json.to }}",
                "message": "={{ $json.response_text }}",
                "options": {}
            },
            "credentials": {
                "twilioApi": {
                    "id": "twilio_cred",
                    "name": "Twilio account"
                }
            }
        }
    
    def _create_respond_node(self, index: int) -> Dict:
        """Create Respond to Twilio node."""
        return {
            "id": self._generate_node_id(),
            "name": "Respond to Twilio",
            "type": "n8n-nodes-base.respondToWebhook",
            "typeVersion": 1.1,
            "position": self._get_position(index),
            "parameters": {
                "respondWith": "text",
                "responseBody": "OK",
                "options": {
                    "responseCode": 200
                }
            }
        }
    
    def _create_error_handler_node(self, index: int, row: int = 0) -> Dict:
        """Create Error Handler node."""
        return {
            "id": self._generate_node_id(),
            "name": "Error Handler",
            "type": "n8n-nodes-base.errorTrigger",
            "typeVersion": 1,
            "position": self._get_position(index, row)
        }
    
    def _create_prepare_error_response_node(self, index: int, row: int = 0) -> Dict:
        """Create Prepare Error Response node."""
        return {
            "id": self._generate_node_id(),
            "name": "Prepare Error Response",
            "type": "n8n-nodes-base.set",
            "typeVersion": 3.4,
            "position": self._get_position(index, row),
            "parameters": {
                "mode": "manual",
                "duplicateItem": False,
                "assignments": {
                    "assignments": [
                        {
                            "id": str(uuid.uuid4()),
                            "name": "error_message",
                            "value": "Sorry, we encountered an issue. Please try again or contact support.",
                            "type": "string"
                        }
                    ]
                },
                "includeOtherFields": True,
                "options": {}
            }
        }
    
    def _create_send_error_node(self, index: int, row: int = 0) -> Dict:
        """Create Send Error Message node."""
        return {
            "id": self._generate_node_id(),
            "name": "Send Error Message",
            "type": "n8n-nodes-base.twilio",
            "typeVersion": 1,
            "position": self._get_position(index, row),
            "parameters": {
                "operation": "send",
                "from": "whatsapp:+14155238886",
                "to": "={{ $json.from_number }}",
                "message": "={{ $json.error_message }}",
                "options": {}
            },
            "credentials": {
                "twilioApi": {
                    "id": "twilio_cred",
                    "name": "Twilio account"
                }
            }
        }


def export_to_n8n(bot_config: Dict[str, Any]) -> Dict[str, Any]:
    """
    Export bot configuration to n8n workflow.
    
    Args:
        bot_config: Bot configuration from build_bot_config()
    
    Returns:
        n8n workflow JSON
    """
    exporter = N8nWorkflowExporter()
    return exporter.export_workflow(bot_config)


def save_n8n_workflow(workflow: Dict[str, Any], filename: str) -> str:
    """
    Save n8n workflow to file.
    
    Args:
        workflow: n8n workflow JSON
        filename: Output filename
    
    Returns:
        Path to saved file
    """
    import os
    output_dir = os.path.join(os.path.dirname(__file__), "output")
    os.makedirs(output_dir, exist_ok=True)
    
    filepath = os.path.join(output_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(workflow, f, indent=2)
    
    return filepath


if __name__ == "__main__":
    # Demo: Export a sample workflow
    from bot_builder_schema import build_bot_config, get_preset_config
    
    print("=" * 60)
    print("N8N WORKFLOW EXPORTER - DEMO")
    print("=" * 60)
    
    # Build config from phone repair preset
    config = build_bot_config(
        business_name="QuickFix Repairs",
        selected_modules=[],
        preset_id="phone_repair"
    )
    
    print(f"\nBot Config: {config['bot_id']}")
    print(f"Modules: {list(config['modules'].keys())}")
    
    # Export to n8n
    workflow = export_to_n8n(config)
    
    print(f"\nWorkflow: {workflow['name']}")
    print(f"Nodes: {len(workflow['nodes'])}")
    
    # Save to file
    filepath = save_n8n_workflow(workflow, f"workflow_{config['bot_id']}.json")
    print(f"\nSaved to: {filepath}")
